/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* src = "Mux_Conductual_2x1_2bits_Estruc.v:1" *)
module Mux_Conductual_2x1_2bits_Estruc(data_out_Estruc, valid_out1_Estruc, clok, valid1, valid2, reset_L, selector, data_in0, data_in1);
  (* src = "Mux_Conductual_2x1_2bits_Estruc.v:12" *)
  wire [1:0] _00_;
  (* src = "Mux_Conductual_2x1_2bits_Estruc.v:12" *)
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  (* src = "Mux_Conductual_2x1_2bits_Estruc.v:4" *)
  input clok;
  (* src = "Mux_Conductual_2x1_2bits_Estruc.v:9" *)
  input [1:0] data_in0;
  (* src = "Mux_Conductual_2x1_2bits_Estruc.v:10" *)
  input [1:0] data_in1;
  (* src = "Mux_Conductual_2x1_2bits_Estruc.v:2" *)
  output [1:0] data_out_Estruc;
  (* src = "Mux_Conductual_2x1_2bits_Estruc.v:7" *)
  input reset_L;
  (* src = "Mux_Conductual_2x1_2bits_Estruc.v:8" *)
  input selector;
  (* src = "Mux_Conductual_2x1_2bits_Estruc.v:5" *)
  input valid1;
  (* src = "Mux_Conductual_2x1_2bits_Estruc.v:6" *)
  input valid2;
  (* src = "Mux_Conductual_2x1_2bits_Estruc.v:3" *)
  output valid_out1_Estruc;
  NAND _22_ (
    .A(data_in1[1]),
    .B(_06_),
    .Y(_17_)
  );
  NAND _23_ (
    .A(_02_),
    .B(_09_),
    .Y(_18_)
  );
  NOR _24_ (
    .A(data_out_Estruc[1]),
    .B(_09_),
    .Y(_19_)
  );
  NOR _25_ (
    .A(_12_),
    .B(_19_),
    .Y(_20_)
  );
  NAND _26_ (
    .A(_18_),
    .B(_20_),
    .Y(_21_)
  );
  NAND _27_ (
    .A(_17_),
    .B(_21_),
    .Y(_00_[1])
  );
  NAND _28_ (
    .A(_07_),
    .B(_10_),
    .Y(_01_)
  );
  NOT _29_ (
    .A(data_in0[1]),
    .Y(_02_)
  );
  NOT _30_ (
    .A(selector),
    .Y(_03_)
  );
  NOT _31_ (
    .A(valid1),
    .Y(_04_)
  );
  NOT _32_ (
    .A(valid2),
    .Y(_05_)
  );
  NOR _33_ (
    .A(_03_),
    .B(_05_),
    .Y(_06_)
  );
  NAND _34_ (
    .A(selector),
    .B(valid2),
    .Y(_07_)
  );
  NAND _35_ (
    .A(data_in1[0]),
    .B(_06_),
    .Y(_08_)
  );
  NOR _36_ (
    .A(selector),
    .B(_04_),
    .Y(_09_)
  );
  NAND _37_ (
    .A(_03_),
    .B(valid1),
    .Y(_10_)
  );
  NOR _38_ (
    .A(data_out_Estruc[0]),
    .B(_09_),
    .Y(_11_)
  );
  NAND _39_ (
    .A(reset_L),
    .B(_07_),
    .Y(_12_)
  );
  NOT _40_ (
    .A(_12_),
    .Y(_13_)
  );
  NOR _41_ (
    .A(data_in0[0]),
    .B(_10_),
    .Y(_14_)
  );
  NOR _42_ (
    .A(_11_),
    .B(_14_),
    .Y(_15_)
  );
  NAND _43_ (
    .A(_13_),
    .B(_15_),
    .Y(_16_)
  );
  NAND _44_ (
    .A(_08_),
    .B(_16_),
    .Y(_00_[0])
  );
  (* src = "Mux_Conductual_2x1_2bits_Estruc.v:12" *)
  DFF _45_ (
    .C(clok),
    .D(_00_[0]),
    .Q(data_out_Estruc[0])
  );
  (* src = "Mux_Conductual_2x1_2bits_Estruc.v:12" *)
  DFF _46_ (
    .C(clok),
    .D(_00_[1]),
    .Q(data_out_Estruc[1])
  );
  (* src = "Mux_Conductual_2x1_2bits_Estruc.v:12" *)
  DFF _47_ (
    .C(clok),
    .D(_01_),
    .Q(valid_out1_Estruc)
  );
endmodule

(* src = "Mux_Conductual_2x1_4bits_Estruc.v:5" *)
module Mux_Conductual_2x1_4bits_Estruc(out2_Estruc, valid_out2_Estruc, clok, valid1, valid2, reset_L, selector, bus1, bus2);
  (* src = "Mux_Conductual_2x1_4bits_Estruc.v:13" *)
  input [3:0] bus1;
  (* src = "Mux_Conductual_2x1_4bits_Estruc.v:14" *)
  input [3:0] bus2;
  (* src = "Mux_Conductual_2x1_4bits_Estruc.v:8" *)
  input clok;
  (* src = "Mux_Conductual_2x1_4bits_Estruc.v:6" *)
  output [3:0] out2_Estruc;
  (* src = "Mux_Conductual_2x1_4bits_Estruc.v:11" *)
  input reset_L;
  (* src = "Mux_Conductual_2x1_4bits_Estruc.v:12" *)
  input selector;
  (* src = "Mux_Conductual_2x1_4bits_Estruc.v:9" *)
  input valid1;
  (* src = "Mux_Conductual_2x1_4bits_Estruc.v:10" *)
  input valid2;
  (* src = "Mux_Conductual_2x1_4bits_Estruc.v:7" *)
  output valid_out2_Estruc;
  (* module_not_derived = 32'd1 *)
  (* src = "Mux_Conductual_2x1_4bits_Estruc.v:20" *)
  Mux_Conductual_2x1_2bits_Estruc xy (
    .clok(clok),
    .data_in0(bus1[1:0]),
    .data_in1(bus2[1:0]),
    .data_out_Estruc(out2_Estruc[1:0]),
    .reset_L(reset_L),
    .selector(selector),
    .valid1(valid1),
    .valid2(valid2),
    .valid_out1_Estruc(valid_out2_Estruc)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "Mux_Conductual_2x1_4bits_Estruc.v:24" *)
  Mux_Conductual_2x1_2bits_Estruc yz (
    .clok(clok),
    .data_in0(bus1[3:2]),
    .data_in1(bus2[3:2]),
    .data_out_Estruc(out2_Estruc[3:2]),
    .reset_L(reset_L),
    .selector(selector),
    .valid1(valid1),
    .valid2(valid2),
    .valid_out1_Estruc(valid_out2_Estruc)
  );
endmodule

(* top =  1  *)
(* src = "Mux_Conductual_4x1_4bits_Estruc.v:4" *)
module Mux_Conductual_4x1_4bits_Estruc(out3_Estruc, valid_out3_Estruc, clok, valid1, valid2, valid3, valid4, reset_L, selector_2bits, bus1, bus2, bus3, bus4);
  (* src = "Mux_Conductual_4x1_4bits_Estruc.v:15" *)
  input [3:0] bus1;
  (* src = "Mux_Conductual_4x1_4bits_Estruc.v:16" *)
  input [3:0] bus2;
  (* src = "Mux_Conductual_4x1_4bits_Estruc.v:17" *)
  input [3:0] bus3;
  (* src = "Mux_Conductual_4x1_4bits_Estruc.v:18" *)
  input [3:0] bus4;
  (* src = "Mux_Conductual_4x1_4bits_Estruc.v:20" *)
  wire [3:0] c1;
  (* src = "Mux_Conductual_4x1_4bits_Estruc.v:21" *)
  wire [3:0] c2;
  (* src = "Mux_Conductual_4x1_4bits_Estruc.v:7" *)
  input clok;
  (* src = "Mux_Conductual_4x1_4bits_Estruc.v:5" *)
  output [3:0] out3_Estruc;
  (* src = "Mux_Conductual_4x1_4bits_Estruc.v:12" *)
  input reset_L;
  (* src = "Mux_Conductual_4x1_4bits_Estruc.v:14" *)
  input [1:0] selector_2bits;
  (* src = "Mux_Conductual_4x1_4bits_Estruc.v:22" *)
  wire v1;
  (* src = "Mux_Conductual_4x1_4bits_Estruc.v:22" *)
  wire v2;
  (* src = "Mux_Conductual_4x1_4bits_Estruc.v:8" *)
  input valid1;
  (* src = "Mux_Conductual_4x1_4bits_Estruc.v:9" *)
  input valid2;
  (* src = "Mux_Conductual_4x1_4bits_Estruc.v:10" *)
  input valid3;
  (* src = "Mux_Conductual_4x1_4bits_Estruc.v:11" *)
  input valid4;
  (* src = "Mux_Conductual_4x1_4bits_Estruc.v:6" *)
  output valid_out3_Estruc;
  (* module_not_derived = 32'd1 *)
  (* src = "Mux_Conductual_4x1_4bits_Estruc.v:33" *)
  Mux_Conductual_2x1_4bits_Estruc dx (
    .bus1(c1),
    .bus2(c2),
    .clok(clok),
    .out2_Estruc(out3_Estruc),
    .reset_L(reset_L),
    .selector(selector_2bits[0]),
    .valid1(v1),
    .valid2(v2),
    .valid_out2_Estruc(valid_out3_Estruc)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "Mux_Conductual_4x1_4bits_Estruc.v:25" *)
  Mux_Conductual_2x1_4bits_Estruc intst (
    .bus1(bus1),
    .bus2(bus3),
    .clok(clok),
    .out2_Estruc(c1),
    .reset_L(reset_L),
    .selector(selector_2bits[1]),
    .valid1(valid1),
    .valid2(valid3),
    .valid_out2_Estruc(v1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "Mux_Conductual_4x1_4bits_Estruc.v:29" *)
  Mux_Conductual_2x1_4bits_Estruc wt (
    .bus1(bus2),
    .bus2(bus4),
    .clok(clok),
    .out2_Estruc(c2),
    .reset_L(reset_L),
    .selector(selector_2bits[1]),
    .valid1(valid2),
    .valid2(valid4),
    .valid_out2_Estruc(v2)
  );
endmodule
