/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "Demux_8x32_Estruc.v:1" *)
module Demux_8x32_Estruc(data_out_8x32_Estruc, valid_out_Estruc, clk_4f, data_in_8x32, selector_clk_4f, valid_in_8x32, reset_L);
  (* src = "Demux_8x32_Estruc.v:12" *)
  wire [31:0] _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  (* src = "Demux_8x32_Estruc.v:4" *)
  input clk_4f;
  (* src = "Demux_8x32_Estruc.v:5" *)
  input [7:0] data_in_8x32;
  (* src = "Demux_8x32_Estruc.v:2" *)
  output [31:0] data_out_8x32_Estruc;
  (* src = "Demux_8x32_Estruc.v:8" *)
  input reset_L;
  (* src = "Demux_8x32_Estruc.v:6" *)
  input [1:0] selector_clk_4f;
  (* src = "Demux_8x32_Estruc.v:7" *)
  input valid_in_8x32;
  (* src = "Demux_8x32_Estruc.v:3" *)
  output valid_out_Estruc;
  NOT _079_ (
    .A(selector_clk_4f[1]),
    .Y(_061_)
  );
  NOT _080_ (
    .A(selector_clk_4f[0]),
    .Y(_062_)
  );
  NOR _081_ (
    .A(selector_clk_4f[1]),
    .B(selector_clk_4f[0]),
    .Y(_063_)
  );
  NOT _082_ (
    .A(_063_),
    .Y(_064_)
  );
  NAND _083_ (
    .A(valid_in_8x32),
    .B(reset_L),
    .Y(_065_)
  );
  NOT _084_ (
    .A(_065_),
    .Y(_066_)
  );
  NOR _085_ (
    .A(_064_),
    .B(_065_),
    .Y(_067_)
  );
  NAND _086_ (
    .A(_063_),
    .B(_066_),
    .Y(_068_)
  );
  NAND _087_ (
    .A(data_in_8x32[0]),
    .B(_067_),
    .Y(_069_)
  );
  NAND _088_ (
    .A(data_out_8x32_Estruc[24]),
    .B(_068_),
    .Y(_070_)
  );
  NAND _089_ (
    .A(_069_),
    .B(_070_),
    .Y(_000_[24])
  );
  NAND _090_ (
    .A(data_in_8x32[1]),
    .B(_067_),
    .Y(_071_)
  );
  NAND _091_ (
    .A(data_out_8x32_Estruc[25]),
    .B(_068_),
    .Y(_072_)
  );
  NAND _092_ (
    .A(_071_),
    .B(_072_),
    .Y(_000_[25])
  );
  NAND _093_ (
    .A(data_in_8x32[2]),
    .B(_067_),
    .Y(_073_)
  );
  NAND _094_ (
    .A(data_out_8x32_Estruc[26]),
    .B(_068_),
    .Y(_074_)
  );
  NAND _095_ (
    .A(_073_),
    .B(_074_),
    .Y(_000_[26])
  );
  NAND _096_ (
    .A(data_in_8x32[3]),
    .B(_067_),
    .Y(_075_)
  );
  NAND _097_ (
    .A(data_out_8x32_Estruc[27]),
    .B(_068_),
    .Y(_076_)
  );
  NAND _098_ (
    .A(_075_),
    .B(_076_),
    .Y(_000_[27])
  );
  NAND _099_ (
    .A(data_in_8x32[4]),
    .B(_067_),
    .Y(_077_)
  );
  NAND _100_ (
    .A(data_out_8x32_Estruc[28]),
    .B(_068_),
    .Y(_078_)
  );
  NAND _101_ (
    .A(_077_),
    .B(_078_),
    .Y(_000_[28])
  );
  NAND _102_ (
    .A(data_in_8x32[5]),
    .B(_067_),
    .Y(_001_)
  );
  NAND _103_ (
    .A(data_out_8x32_Estruc[29]),
    .B(_068_),
    .Y(_002_)
  );
  NAND _104_ (
    .A(_001_),
    .B(_002_),
    .Y(_000_[29])
  );
  NAND _105_ (
    .A(data_in_8x32[6]),
    .B(_067_),
    .Y(_003_)
  );
  NAND _106_ (
    .A(data_out_8x32_Estruc[30]),
    .B(_068_),
    .Y(_004_)
  );
  NAND _107_ (
    .A(_003_),
    .B(_004_),
    .Y(_000_[30])
  );
  NAND _108_ (
    .A(data_in_8x32[7]),
    .B(_067_),
    .Y(_005_)
  );
  NAND _109_ (
    .A(data_out_8x32_Estruc[31]),
    .B(_068_),
    .Y(_006_)
  );
  NAND _110_ (
    .A(_005_),
    .B(_006_),
    .Y(_000_[31])
  );
  NOR _111_ (
    .A(_061_),
    .B(_062_),
    .Y(_007_)
  );
  NAND _112_ (
    .A(selector_clk_4f[1]),
    .B(selector_clk_4f[0]),
    .Y(_008_)
  );
  NAND _113_ (
    .A(data_in_8x32[0]),
    .B(_007_),
    .Y(_009_)
  );
  NAND _114_ (
    .A(data_out_8x32_Estruc[0]),
    .B(_008_),
    .Y(_010_)
  );
  NAND _115_ (
    .A(_009_),
    .B(_010_),
    .Y(_000_[0])
  );
  NAND _116_ (
    .A(data_in_8x32[1]),
    .B(_007_),
    .Y(_011_)
  );
  NAND _117_ (
    .A(data_out_8x32_Estruc[1]),
    .B(_008_),
    .Y(_012_)
  );
  NAND _118_ (
    .A(_011_),
    .B(_012_),
    .Y(_000_[1])
  );
  NAND _119_ (
    .A(data_in_8x32[2]),
    .B(_007_),
    .Y(_013_)
  );
  NAND _120_ (
    .A(data_out_8x32_Estruc[2]),
    .B(_008_),
    .Y(_014_)
  );
  NAND _121_ (
    .A(_013_),
    .B(_014_),
    .Y(_000_[2])
  );
  NAND _122_ (
    .A(data_in_8x32[3]),
    .B(_007_),
    .Y(_015_)
  );
  NAND _123_ (
    .A(data_out_8x32_Estruc[3]),
    .B(_008_),
    .Y(_016_)
  );
  NAND _124_ (
    .A(_015_),
    .B(_016_),
    .Y(_000_[3])
  );
  NAND _125_ (
    .A(data_in_8x32[4]),
    .B(_007_),
    .Y(_017_)
  );
  NAND _126_ (
    .A(data_out_8x32_Estruc[4]),
    .B(_008_),
    .Y(_018_)
  );
  NAND _127_ (
    .A(_017_),
    .B(_018_),
    .Y(_000_[4])
  );
  NAND _128_ (
    .A(data_in_8x32[5]),
    .B(_007_),
    .Y(_019_)
  );
  NAND _129_ (
    .A(data_out_8x32_Estruc[5]),
    .B(_008_),
    .Y(_020_)
  );
  NAND _130_ (
    .A(_019_),
    .B(_020_),
    .Y(_000_[5])
  );
  NAND _131_ (
    .A(data_in_8x32[6]),
    .B(_007_),
    .Y(_021_)
  );
  NAND _132_ (
    .A(data_out_8x32_Estruc[6]),
    .B(_008_),
    .Y(_022_)
  );
  NAND _133_ (
    .A(_021_),
    .B(_022_),
    .Y(_000_[6])
  );
  NAND _134_ (
    .A(data_in_8x32[7]),
    .B(_007_),
    .Y(_023_)
  );
  NAND _135_ (
    .A(data_out_8x32_Estruc[7]),
    .B(_008_),
    .Y(_024_)
  );
  NAND _136_ (
    .A(_023_),
    .B(_024_),
    .Y(_000_[7])
  );
  NOR _137_ (
    .A(selector_clk_4f[1]),
    .B(_062_),
    .Y(_025_)
  );
  NAND _138_ (
    .A(_061_),
    .B(selector_clk_4f[0]),
    .Y(_026_)
  );
  NAND _139_ (
    .A(data_in_8x32[0]),
    .B(_025_),
    .Y(_027_)
  );
  NAND _140_ (
    .A(data_out_8x32_Estruc[16]),
    .B(_026_),
    .Y(_028_)
  );
  NAND _141_ (
    .A(_027_),
    .B(_028_),
    .Y(_000_[16])
  );
  NAND _142_ (
    .A(data_in_8x32[1]),
    .B(_025_),
    .Y(_029_)
  );
  NAND _143_ (
    .A(data_out_8x32_Estruc[17]),
    .B(_026_),
    .Y(_030_)
  );
  NAND _144_ (
    .A(_029_),
    .B(_030_),
    .Y(_000_[17])
  );
  NAND _145_ (
    .A(data_in_8x32[2]),
    .B(_025_),
    .Y(_031_)
  );
  NAND _146_ (
    .A(data_out_8x32_Estruc[18]),
    .B(_026_),
    .Y(_032_)
  );
  NAND _147_ (
    .A(_031_),
    .B(_032_),
    .Y(_000_[18])
  );
  NAND _148_ (
    .A(data_in_8x32[3]),
    .B(_025_),
    .Y(_033_)
  );
  NAND _149_ (
    .A(data_out_8x32_Estruc[19]),
    .B(_026_),
    .Y(_034_)
  );
  NAND _150_ (
    .A(_033_),
    .B(_034_),
    .Y(_000_[19])
  );
  NAND _151_ (
    .A(data_in_8x32[4]),
    .B(_025_),
    .Y(_035_)
  );
  NAND _152_ (
    .A(data_out_8x32_Estruc[20]),
    .B(_026_),
    .Y(_036_)
  );
  NAND _153_ (
    .A(_035_),
    .B(_036_),
    .Y(_000_[20])
  );
  NAND _154_ (
    .A(data_in_8x32[5]),
    .B(_025_),
    .Y(_037_)
  );
  NAND _155_ (
    .A(data_out_8x32_Estruc[21]),
    .B(_026_),
    .Y(_038_)
  );
  NAND _156_ (
    .A(_037_),
    .B(_038_),
    .Y(_000_[21])
  );
  NAND _157_ (
    .A(data_in_8x32[6]),
    .B(_025_),
    .Y(_039_)
  );
  NAND _158_ (
    .A(data_out_8x32_Estruc[22]),
    .B(_026_),
    .Y(_040_)
  );
  NAND _159_ (
    .A(_039_),
    .B(_040_),
    .Y(_000_[22])
  );
  NAND _160_ (
    .A(data_in_8x32[7]),
    .B(_025_),
    .Y(_041_)
  );
  NAND _161_ (
    .A(data_out_8x32_Estruc[23]),
    .B(_026_),
    .Y(_042_)
  );
  NAND _162_ (
    .A(_041_),
    .B(_042_),
    .Y(_000_[23])
  );
  NOR _163_ (
    .A(_061_),
    .B(selector_clk_4f[0]),
    .Y(_043_)
  );
  NAND _164_ (
    .A(selector_clk_4f[1]),
    .B(_062_),
    .Y(_044_)
  );
  NAND _165_ (
    .A(data_in_8x32[0]),
    .B(_043_),
    .Y(_045_)
  );
  NAND _166_ (
    .A(data_out_8x32_Estruc[8]),
    .B(_044_),
    .Y(_046_)
  );
  NAND _167_ (
    .A(_045_),
    .B(_046_),
    .Y(_000_[8])
  );
  NAND _168_ (
    .A(data_in_8x32[1]),
    .B(_043_),
    .Y(_047_)
  );
  NAND _169_ (
    .A(data_out_8x32_Estruc[9]),
    .B(_044_),
    .Y(_048_)
  );
  NAND _170_ (
    .A(_047_),
    .B(_048_),
    .Y(_000_[9])
  );
  NAND _171_ (
    .A(data_in_8x32[2]),
    .B(_043_),
    .Y(_049_)
  );
  NAND _172_ (
    .A(data_out_8x32_Estruc[10]),
    .B(_044_),
    .Y(_050_)
  );
  NAND _173_ (
    .A(_049_),
    .B(_050_),
    .Y(_000_[10])
  );
  NAND _174_ (
    .A(data_in_8x32[3]),
    .B(_043_),
    .Y(_051_)
  );
  NAND _175_ (
    .A(data_out_8x32_Estruc[11]),
    .B(_044_),
    .Y(_052_)
  );
  NAND _176_ (
    .A(_051_),
    .B(_052_),
    .Y(_000_[11])
  );
  NAND _177_ (
    .A(data_in_8x32[4]),
    .B(_043_),
    .Y(_053_)
  );
  NAND _178_ (
    .A(data_out_8x32_Estruc[12]),
    .B(_044_),
    .Y(_054_)
  );
  NAND _179_ (
    .A(_053_),
    .B(_054_),
    .Y(_000_[12])
  );
  NAND _180_ (
    .A(data_in_8x32[5]),
    .B(_043_),
    .Y(_055_)
  );
  NAND _181_ (
    .A(data_out_8x32_Estruc[13]),
    .B(_044_),
    .Y(_056_)
  );
  NAND _182_ (
    .A(_055_),
    .B(_056_),
    .Y(_000_[13])
  );
  NAND _183_ (
    .A(data_in_8x32[6]),
    .B(_043_),
    .Y(_057_)
  );
  NAND _184_ (
    .A(data_out_8x32_Estruc[14]),
    .B(_044_),
    .Y(_058_)
  );
  NAND _185_ (
    .A(_057_),
    .B(_058_),
    .Y(_000_[14])
  );
  NAND _186_ (
    .A(data_in_8x32[7]),
    .B(_043_),
    .Y(_059_)
  );
  NAND _187_ (
    .A(data_out_8x32_Estruc[15]),
    .B(_044_),
    .Y(_060_)
  );
  NAND _188_ (
    .A(_059_),
    .B(_060_),
    .Y(_000_[15])
  );
  (* src = "Demux_8x32_Estruc.v:12" *)
  DFF _189_ (
    .C(clk_4f),
    .D(_000_[0]),
    .Q(data_out_8x32_Estruc[0])
  );
  (* src = "Demux_8x32_Estruc.v:12" *)
  DFF _190_ (
    .C(clk_4f),
    .D(_000_[1]),
    .Q(data_out_8x32_Estruc[1])
  );
  (* src = "Demux_8x32_Estruc.v:12" *)
  DFF _191_ (
    .C(clk_4f),
    .D(_000_[2]),
    .Q(data_out_8x32_Estruc[2])
  );
  (* src = "Demux_8x32_Estruc.v:12" *)
  DFF _192_ (
    .C(clk_4f),
    .D(_000_[3]),
    .Q(data_out_8x32_Estruc[3])
  );
  (* src = "Demux_8x32_Estruc.v:12" *)
  DFF _193_ (
    .C(clk_4f),
    .D(_000_[4]),
    .Q(data_out_8x32_Estruc[4])
  );
  (* src = "Demux_8x32_Estruc.v:12" *)
  DFF _194_ (
    .C(clk_4f),
    .D(_000_[5]),
    .Q(data_out_8x32_Estruc[5])
  );
  (* src = "Demux_8x32_Estruc.v:12" *)
  DFF _195_ (
    .C(clk_4f),
    .D(_000_[6]),
    .Q(data_out_8x32_Estruc[6])
  );
  (* src = "Demux_8x32_Estruc.v:12" *)
  DFF _196_ (
    .C(clk_4f),
    .D(_000_[7]),
    .Q(data_out_8x32_Estruc[7])
  );
  (* src = "Demux_8x32_Estruc.v:12" *)
  DFF _197_ (
    .C(clk_4f),
    .D(_000_[8]),
    .Q(data_out_8x32_Estruc[8])
  );
  (* src = "Demux_8x32_Estruc.v:12" *)
  DFF _198_ (
    .C(clk_4f),
    .D(_000_[9]),
    .Q(data_out_8x32_Estruc[9])
  );
  (* src = "Demux_8x32_Estruc.v:12" *)
  DFF _199_ (
    .C(clk_4f),
    .D(_000_[10]),
    .Q(data_out_8x32_Estruc[10])
  );
  (* src = "Demux_8x32_Estruc.v:12" *)
  DFF _200_ (
    .C(clk_4f),
    .D(_000_[11]),
    .Q(data_out_8x32_Estruc[11])
  );
  (* src = "Demux_8x32_Estruc.v:12" *)
  DFF _201_ (
    .C(clk_4f),
    .D(_000_[12]),
    .Q(data_out_8x32_Estruc[12])
  );
  (* src = "Demux_8x32_Estruc.v:12" *)
  DFF _202_ (
    .C(clk_4f),
    .D(_000_[13]),
    .Q(data_out_8x32_Estruc[13])
  );
  (* src = "Demux_8x32_Estruc.v:12" *)
  DFF _203_ (
    .C(clk_4f),
    .D(_000_[14]),
    .Q(data_out_8x32_Estruc[14])
  );
  (* src = "Demux_8x32_Estruc.v:12" *)
  DFF _204_ (
    .C(clk_4f),
    .D(_000_[15]),
    .Q(data_out_8x32_Estruc[15])
  );
  (* src = "Demux_8x32_Estruc.v:12" *)
  DFF _205_ (
    .C(clk_4f),
    .D(_000_[16]),
    .Q(data_out_8x32_Estruc[16])
  );
  (* src = "Demux_8x32_Estruc.v:12" *)
  DFF _206_ (
    .C(clk_4f),
    .D(_000_[17]),
    .Q(data_out_8x32_Estruc[17])
  );
  (* src = "Demux_8x32_Estruc.v:12" *)
  DFF _207_ (
    .C(clk_4f),
    .D(_000_[18]),
    .Q(data_out_8x32_Estruc[18])
  );
  (* src = "Demux_8x32_Estruc.v:12" *)
  DFF _208_ (
    .C(clk_4f),
    .D(_000_[19]),
    .Q(data_out_8x32_Estruc[19])
  );
  (* src = "Demux_8x32_Estruc.v:12" *)
  DFF _209_ (
    .C(clk_4f),
    .D(_000_[20]),
    .Q(data_out_8x32_Estruc[20])
  );
  (* src = "Demux_8x32_Estruc.v:12" *)
  DFF _210_ (
    .C(clk_4f),
    .D(_000_[21]),
    .Q(data_out_8x32_Estruc[21])
  );
  (* src = "Demux_8x32_Estruc.v:12" *)
  DFF _211_ (
    .C(clk_4f),
    .D(_000_[22]),
    .Q(data_out_8x32_Estruc[22])
  );
  (* src = "Demux_8x32_Estruc.v:12" *)
  DFF _212_ (
    .C(clk_4f),
    .D(_000_[23]),
    .Q(data_out_8x32_Estruc[23])
  );
  (* src = "Demux_8x32_Estruc.v:12" *)
  DFF _213_ (
    .C(clk_4f),
    .D(_000_[24]),
    .Q(data_out_8x32_Estruc[24])
  );
  (* src = "Demux_8x32_Estruc.v:12" *)
  DFF _214_ (
    .C(clk_4f),
    .D(_000_[25]),
    .Q(data_out_8x32_Estruc[25])
  );
  (* src = "Demux_8x32_Estruc.v:12" *)
  DFF _215_ (
    .C(clk_4f),
    .D(_000_[26]),
    .Q(data_out_8x32_Estruc[26])
  );
  (* src = "Demux_8x32_Estruc.v:12" *)
  DFF _216_ (
    .C(clk_4f),
    .D(_000_[27]),
    .Q(data_out_8x32_Estruc[27])
  );
  (* src = "Demux_8x32_Estruc.v:12" *)
  DFF _217_ (
    .C(clk_4f),
    .D(_000_[28]),
    .Q(data_out_8x32_Estruc[28])
  );
  (* src = "Demux_8x32_Estruc.v:12" *)
  DFF _218_ (
    .C(clk_4f),
    .D(_000_[29]),
    .Q(data_out_8x32_Estruc[29])
  );
  (* src = "Demux_8x32_Estruc.v:12" *)
  DFF _219_ (
    .C(clk_4f),
    .D(_000_[30]),
    .Q(data_out_8x32_Estruc[30])
  );
  (* src = "Demux_8x32_Estruc.v:12" *)
  DFF _220_ (
    .C(clk_4f),
    .D(_000_[31]),
    .Q(data_out_8x32_Estruc[31])
  );
  (* src = "Demux_8x32_Estruc.v:12" *)
  DFF _221_ (
    .C(clk_4f),
    .D(valid_in_8x32),
    .Q(valid_out_Estruc)
  );
endmodule
