/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* src = "Demux_8x32.v:1" *)
module Demux_8x32(data_out_8x32, valid_out_8x32, clk_4f, data_in_8x32, valid_in_8x32, reset_L);
  (* src = "Demux_8x32.v:17" *)
  wire [31:0] _000_;
  (* src = "Demux_8x32.v:17" *)
  wire [1:0] _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  (* src = "Demux_8x32.v:4" *)
  input clk_4f;
  (* src = "Demux_8x32.v:5" *)
  input [7:0] data_in_8x32;
  (* src = "Demux_8x32.v:2" *)
  output [31:0] data_out_8x32;
  (* src = "Demux_8x32.v:7" *)
  input reset_L;
  (* src = "Demux_8x32.v:9" *)
  wire [1:0] selector_clk_4f;
  (* src = "Demux_8x32.v:6" *)
  input valid_in_8x32;
  (* src = "Demux_8x32.v:3" *)
  output valid_out_8x32;
  NOT _136_ (
    .A(selector_clk_4f[0]),
    .Y(_115_)
  );
  NOT _137_ (
    .A(selector_clk_4f[1]),
    .Y(_116_)
  );
  NOT _138_ (
    .A(data_in_8x32[0]),
    .Y(_117_)
  );
  NOT _139_ (
    .A(data_in_8x32[1]),
    .Y(_118_)
  );
  NOT _140_ (
    .A(data_in_8x32[2]),
    .Y(_119_)
  );
  NOT _141_ (
    .A(data_in_8x32[3]),
    .Y(_120_)
  );
  NOT _142_ (
    .A(data_in_8x32[4]),
    .Y(_121_)
  );
  NOT _143_ (
    .A(data_in_8x32[5]),
    .Y(_122_)
  );
  NOT _144_ (
    .A(data_in_8x32[6]),
    .Y(_123_)
  );
  NOT _145_ (
    .A(data_in_8x32[7]),
    .Y(_124_)
  );
  NOT _146_ (
    .A(reset_L),
    .Y(_125_)
  );
  NOT _147_ (
    .A(valid_in_8x32),
    .Y(_126_)
  );
  NOR _148_ (
    .A(selector_clk_4f[0]),
    .B(_126_),
    .Y(_127_)
  );
  NAND _149_ (
    .A(_115_),
    .B(valid_in_8x32),
    .Y(_128_)
  );
  NAND _150_ (
    .A(selector_clk_4f[1]),
    .B(reset_L),
    .Y(_129_)
  );
  NOT _151_ (
    .A(_129_),
    .Y(_130_)
  );
  NOR _152_ (
    .A(_128_),
    .B(_129_),
    .Y(_131_)
  );
  NAND _153_ (
    .A(_127_),
    .B(_130_),
    .Y(_132_)
  );
  NOR _154_ (
    .A(data_in_8x32[0]),
    .B(_132_),
    .Y(_133_)
  );
  NAND _155_ (
    .A(data_out_8x32[8]),
    .B(reset_L),
    .Y(_134_)
  );
  NOT _156_ (
    .A(_134_),
    .Y(_135_)
  );
  NOR _157_ (
    .A(_131_),
    .B(_135_),
    .Y(_002_)
  );
  NOR _158_ (
    .A(_133_),
    .B(_002_),
    .Y(_000_[8])
  );
  NOR _159_ (
    .A(data_in_8x32[1]),
    .B(_132_),
    .Y(_003_)
  );
  NAND _160_ (
    .A(data_out_8x32[9]),
    .B(reset_L),
    .Y(_004_)
  );
  NOT _161_ (
    .A(_004_),
    .Y(_005_)
  );
  NOR _162_ (
    .A(_131_),
    .B(_005_),
    .Y(_006_)
  );
  NOR _163_ (
    .A(_003_),
    .B(_006_),
    .Y(_000_[9])
  );
  NOR _164_ (
    .A(data_in_8x32[2]),
    .B(_132_),
    .Y(_007_)
  );
  NAND _165_ (
    .A(data_out_8x32[10]),
    .B(reset_L),
    .Y(_008_)
  );
  NOT _166_ (
    .A(_008_),
    .Y(_009_)
  );
  NOR _167_ (
    .A(_131_),
    .B(_009_),
    .Y(_010_)
  );
  NOR _168_ (
    .A(_007_),
    .B(_010_),
    .Y(_000_[10])
  );
  NOR _169_ (
    .A(data_in_8x32[3]),
    .B(_132_),
    .Y(_011_)
  );
  NAND _170_ (
    .A(data_out_8x32[11]),
    .B(reset_L),
    .Y(_012_)
  );
  NOT _171_ (
    .A(_012_),
    .Y(_013_)
  );
  NOR _172_ (
    .A(_131_),
    .B(_013_),
    .Y(_014_)
  );
  NOR _173_ (
    .A(_011_),
    .B(_014_),
    .Y(_000_[11])
  );
  NOR _174_ (
    .A(data_in_8x32[4]),
    .B(_132_),
    .Y(_015_)
  );
  NAND _175_ (
    .A(data_out_8x32[12]),
    .B(reset_L),
    .Y(_016_)
  );
  NOT _176_ (
    .A(_016_),
    .Y(_017_)
  );
  NOR _177_ (
    .A(_131_),
    .B(_017_),
    .Y(_018_)
  );
  NOR _178_ (
    .A(_015_),
    .B(_018_),
    .Y(_000_[12])
  );
  NOR _179_ (
    .A(data_in_8x32[5]),
    .B(_132_),
    .Y(_019_)
  );
  NAND _180_ (
    .A(data_out_8x32[13]),
    .B(reset_L),
    .Y(_020_)
  );
  NOT _181_ (
    .A(_020_),
    .Y(_021_)
  );
  NOR _182_ (
    .A(_131_),
    .B(_021_),
    .Y(_022_)
  );
  NOR _183_ (
    .A(_019_),
    .B(_022_),
    .Y(_000_[13])
  );
  NOR _184_ (
    .A(data_in_8x32[6]),
    .B(_132_),
    .Y(_023_)
  );
  NAND _185_ (
    .A(data_out_8x32[14]),
    .B(reset_L),
    .Y(_024_)
  );
  NOT _186_ (
    .A(_024_),
    .Y(_025_)
  );
  NOR _187_ (
    .A(_131_),
    .B(_025_),
    .Y(_026_)
  );
  NOR _188_ (
    .A(_023_),
    .B(_026_),
    .Y(_000_[14])
  );
  NOR _189_ (
    .A(data_in_8x32[7]),
    .B(_132_),
    .Y(_027_)
  );
  NAND _190_ (
    .A(data_out_8x32[15]),
    .B(reset_L),
    .Y(_028_)
  );
  NOT _191_ (
    .A(_028_),
    .Y(_029_)
  );
  NOR _192_ (
    .A(_131_),
    .B(_029_),
    .Y(_030_)
  );
  NOR _193_ (
    .A(_027_),
    .B(_030_),
    .Y(_000_[15])
  );
  NAND _194_ (
    .A(selector_clk_4f[0]),
    .B(valid_in_8x32),
    .Y(_031_)
  );
  NOR _195_ (
    .A(_129_),
    .B(_031_),
    .Y(_032_)
  );
  NAND _196_ (
    .A(_117_),
    .B(_032_),
    .Y(_033_)
  );
  NOR _197_ (
    .A(data_out_8x32[0]),
    .B(_032_),
    .Y(_034_)
  );
  NAND _198_ (
    .A(reset_L),
    .B(_033_),
    .Y(_035_)
  );
  NOR _199_ (
    .A(_034_),
    .B(_035_),
    .Y(_000_[0])
  );
  NAND _200_ (
    .A(_118_),
    .B(_032_),
    .Y(_036_)
  );
  NOR _201_ (
    .A(data_out_8x32[1]),
    .B(_032_),
    .Y(_037_)
  );
  NAND _202_ (
    .A(reset_L),
    .B(_036_),
    .Y(_038_)
  );
  NOR _203_ (
    .A(_037_),
    .B(_038_),
    .Y(_000_[1])
  );
  NAND _204_ (
    .A(_119_),
    .B(_032_),
    .Y(_039_)
  );
  NOR _205_ (
    .A(data_out_8x32[2]),
    .B(_032_),
    .Y(_040_)
  );
  NAND _206_ (
    .A(reset_L),
    .B(_039_),
    .Y(_041_)
  );
  NOR _207_ (
    .A(_040_),
    .B(_041_),
    .Y(_000_[2])
  );
  NAND _208_ (
    .A(_120_),
    .B(_032_),
    .Y(_042_)
  );
  NOR _209_ (
    .A(data_out_8x32[3]),
    .B(_032_),
    .Y(_043_)
  );
  NAND _210_ (
    .A(reset_L),
    .B(_042_),
    .Y(_044_)
  );
  NOR _211_ (
    .A(_043_),
    .B(_044_),
    .Y(_000_[3])
  );
  NAND _212_ (
    .A(_121_),
    .B(_032_),
    .Y(_045_)
  );
  NOR _213_ (
    .A(data_out_8x32[4]),
    .B(_032_),
    .Y(_046_)
  );
  NAND _214_ (
    .A(reset_L),
    .B(_045_),
    .Y(_047_)
  );
  NOR _215_ (
    .A(_046_),
    .B(_047_),
    .Y(_000_[4])
  );
  NAND _216_ (
    .A(_122_),
    .B(_032_),
    .Y(_048_)
  );
  NOR _217_ (
    .A(data_out_8x32[5]),
    .B(_032_),
    .Y(_049_)
  );
  NAND _218_ (
    .A(reset_L),
    .B(_048_),
    .Y(_050_)
  );
  NOR _219_ (
    .A(_049_),
    .B(_050_),
    .Y(_000_[5])
  );
  NAND _220_ (
    .A(_123_),
    .B(_032_),
    .Y(_051_)
  );
  NOR _221_ (
    .A(data_out_8x32[6]),
    .B(_032_),
    .Y(_052_)
  );
  NAND _222_ (
    .A(reset_L),
    .B(_051_),
    .Y(_053_)
  );
  NOR _223_ (
    .A(_052_),
    .B(_053_),
    .Y(_000_[6])
  );
  NAND _224_ (
    .A(_124_),
    .B(_032_),
    .Y(_054_)
  );
  NOR _225_ (
    .A(data_out_8x32[7]),
    .B(_032_),
    .Y(_055_)
  );
  NAND _226_ (
    .A(reset_L),
    .B(_054_),
    .Y(_056_)
  );
  NOR _227_ (
    .A(_055_),
    .B(_056_),
    .Y(_000_[7])
  );
  NOR _228_ (
    .A(selector_clk_4f[1]),
    .B(_031_),
    .Y(_057_)
  );
  NOR _229_ (
    .A(_125_),
    .B(_057_),
    .Y(_058_)
  );
  NAND _230_ (
    .A(data_out_8x32[16]),
    .B(_058_),
    .Y(_059_)
  );
  NOR _231_ (
    .A(selector_clk_4f[1]),
    .B(_125_),
    .Y(_060_)
  );
  NAND _232_ (
    .A(_116_),
    .B(reset_L),
    .Y(_061_)
  );
  NOR _233_ (
    .A(_031_),
    .B(_061_),
    .Y(_062_)
  );
  NAND _234_ (
    .A(data_in_8x32[0]),
    .B(_062_),
    .Y(_063_)
  );
  NAND _235_ (
    .A(_059_),
    .B(_063_),
    .Y(_000_[16])
  );
  NAND _236_ (
    .A(data_out_8x32[17]),
    .B(_058_),
    .Y(_064_)
  );
  NAND _237_ (
    .A(data_in_8x32[1]),
    .B(_062_),
    .Y(_065_)
  );
  NAND _238_ (
    .A(_064_),
    .B(_065_),
    .Y(_000_[17])
  );
  NAND _239_ (
    .A(data_out_8x32[18]),
    .B(_058_),
    .Y(_066_)
  );
  NAND _240_ (
    .A(data_in_8x32[2]),
    .B(_062_),
    .Y(_067_)
  );
  NAND _241_ (
    .A(_066_),
    .B(_067_),
    .Y(_000_[18])
  );
  NAND _242_ (
    .A(data_out_8x32[19]),
    .B(_058_),
    .Y(_068_)
  );
  NAND _243_ (
    .A(data_in_8x32[3]),
    .B(_062_),
    .Y(_069_)
  );
  NAND _244_ (
    .A(_068_),
    .B(_069_),
    .Y(_000_[19])
  );
  NAND _245_ (
    .A(data_out_8x32[20]),
    .B(_058_),
    .Y(_070_)
  );
  NAND _246_ (
    .A(data_in_8x32[4]),
    .B(_062_),
    .Y(_071_)
  );
  NAND _247_ (
    .A(_070_),
    .B(_071_),
    .Y(_000_[20])
  );
  NAND _248_ (
    .A(data_out_8x32[21]),
    .B(_058_),
    .Y(_072_)
  );
  NAND _249_ (
    .A(data_in_8x32[5]),
    .B(_062_),
    .Y(_073_)
  );
  NAND _250_ (
    .A(_072_),
    .B(_073_),
    .Y(_000_[21])
  );
  NAND _251_ (
    .A(data_out_8x32[22]),
    .B(_058_),
    .Y(_074_)
  );
  NAND _252_ (
    .A(data_in_8x32[6]),
    .B(_062_),
    .Y(_075_)
  );
  NAND _253_ (
    .A(_074_),
    .B(_075_),
    .Y(_000_[22])
  );
  NAND _254_ (
    .A(data_out_8x32[23]),
    .B(_058_),
    .Y(_076_)
  );
  NAND _255_ (
    .A(data_in_8x32[7]),
    .B(_062_),
    .Y(_077_)
  );
  NAND _256_ (
    .A(_076_),
    .B(_077_),
    .Y(_000_[23])
  );
  NOR _257_ (
    .A(_128_),
    .B(_061_),
    .Y(_078_)
  );
  NAND _258_ (
    .A(_127_),
    .B(_060_),
    .Y(_079_)
  );
  NOR _259_ (
    .A(data_in_8x32[0]),
    .B(_079_),
    .Y(_080_)
  );
  NAND _260_ (
    .A(reset_L),
    .B(data_out_8x32[24]),
    .Y(_081_)
  );
  NOT _261_ (
    .A(_081_),
    .Y(_082_)
  );
  NOR _262_ (
    .A(_078_),
    .B(_082_),
    .Y(_083_)
  );
  NOR _263_ (
    .A(_080_),
    .B(_083_),
    .Y(_000_[24])
  );
  NOR _264_ (
    .A(data_in_8x32[1]),
    .B(_079_),
    .Y(_084_)
  );
  NAND _265_ (
    .A(reset_L),
    .B(data_out_8x32[25]),
    .Y(_085_)
  );
  NOT _266_ (
    .A(_085_),
    .Y(_086_)
  );
  NOR _267_ (
    .A(_078_),
    .B(_086_),
    .Y(_087_)
  );
  NOR _268_ (
    .A(_084_),
    .B(_087_),
    .Y(_000_[25])
  );
  NOR _269_ (
    .A(data_in_8x32[2]),
    .B(_079_),
    .Y(_088_)
  );
  NAND _270_ (
    .A(reset_L),
    .B(data_out_8x32[26]),
    .Y(_089_)
  );
  NOT _271_ (
    .A(_089_),
    .Y(_090_)
  );
  NOR _272_ (
    .A(_078_),
    .B(_090_),
    .Y(_091_)
  );
  NOR _273_ (
    .A(_088_),
    .B(_091_),
    .Y(_000_[26])
  );
  NOR _274_ (
    .A(data_in_8x32[3]),
    .B(_079_),
    .Y(_092_)
  );
  NAND _275_ (
    .A(reset_L),
    .B(data_out_8x32[27]),
    .Y(_093_)
  );
  NOT _276_ (
    .A(_093_),
    .Y(_094_)
  );
  NOR _277_ (
    .A(_078_),
    .B(_094_),
    .Y(_095_)
  );
  NOR _278_ (
    .A(_092_),
    .B(_095_),
    .Y(_000_[27])
  );
  NOR _279_ (
    .A(data_in_8x32[4]),
    .B(_079_),
    .Y(_096_)
  );
  NAND _280_ (
    .A(reset_L),
    .B(data_out_8x32[28]),
    .Y(_097_)
  );
  NOT _281_ (
    .A(_097_),
    .Y(_098_)
  );
  NOR _282_ (
    .A(_078_),
    .B(_098_),
    .Y(_099_)
  );
  NOR _283_ (
    .A(_096_),
    .B(_099_),
    .Y(_000_[28])
  );
  NOR _284_ (
    .A(data_in_8x32[5]),
    .B(_079_),
    .Y(_100_)
  );
  NAND _285_ (
    .A(reset_L),
    .B(data_out_8x32[29]),
    .Y(_101_)
  );
  NOT _286_ (
    .A(_101_),
    .Y(_102_)
  );
  NOR _287_ (
    .A(_078_),
    .B(_102_),
    .Y(_103_)
  );
  NOR _288_ (
    .A(_100_),
    .B(_103_),
    .Y(_000_[29])
  );
  NOR _289_ (
    .A(data_in_8x32[6]),
    .B(_079_),
    .Y(_104_)
  );
  NAND _290_ (
    .A(reset_L),
    .B(data_out_8x32[30]),
    .Y(_105_)
  );
  NOT _291_ (
    .A(_105_),
    .Y(_106_)
  );
  NOR _292_ (
    .A(_078_),
    .B(_106_),
    .Y(_107_)
  );
  NOR _293_ (
    .A(_104_),
    .B(_107_),
    .Y(_000_[30])
  );
  NOR _294_ (
    .A(data_in_8x32[7]),
    .B(_079_),
    .Y(_108_)
  );
  NAND _295_ (
    .A(reset_L),
    .B(data_out_8x32[31]),
    .Y(_109_)
  );
  NOT _296_ (
    .A(_109_),
    .Y(_110_)
  );
  NOR _297_ (
    .A(_078_),
    .B(_110_),
    .Y(_111_)
  );
  NOR _298_ (
    .A(_108_),
    .B(_111_),
    .Y(_000_[31])
  );
  NOR _299_ (
    .A(_115_),
    .B(valid_in_8x32),
    .Y(_112_)
  );
  NOR _300_ (
    .A(_125_),
    .B(_112_),
    .Y(_113_)
  );
  NAND _301_ (
    .A(_128_),
    .B(_113_),
    .Y(_001_[0])
  );
  NAND _302_ (
    .A(selector_clk_4f[1]),
    .B(_031_),
    .Y(_114_)
  );
  NAND _303_ (
    .A(_058_),
    .B(_114_),
    .Y(_001_[1])
  );
  (* src = "Demux_8x32.v:17" *)
  DFF _304_ (
    .C(clk_4f),
    .D(_001_[0]),
    .Q(selector_clk_4f[0])
  );
  (* src = "Demux_8x32.v:17" *)
  DFF _305_ (
    .C(clk_4f),
    .D(_001_[1]),
    .Q(selector_clk_4f[1])
  );
  (* src = "Demux_8x32.v:17" *)
  DFF _306_ (
    .C(clk_4f),
    .D(_000_[0]),
    .Q(data_out_8x32[0])
  );
  (* src = "Demux_8x32.v:17" *)
  DFF _307_ (
    .C(clk_4f),
    .D(_000_[1]),
    .Q(data_out_8x32[1])
  );
  (* src = "Demux_8x32.v:17" *)
  DFF _308_ (
    .C(clk_4f),
    .D(_000_[2]),
    .Q(data_out_8x32[2])
  );
  (* src = "Demux_8x32.v:17" *)
  DFF _309_ (
    .C(clk_4f),
    .D(_000_[3]),
    .Q(data_out_8x32[3])
  );
  (* src = "Demux_8x32.v:17" *)
  DFF _310_ (
    .C(clk_4f),
    .D(_000_[4]),
    .Q(data_out_8x32[4])
  );
  (* src = "Demux_8x32.v:17" *)
  DFF _311_ (
    .C(clk_4f),
    .D(_000_[5]),
    .Q(data_out_8x32[5])
  );
  (* src = "Demux_8x32.v:17" *)
  DFF _312_ (
    .C(clk_4f),
    .D(_000_[6]),
    .Q(data_out_8x32[6])
  );
  (* src = "Demux_8x32.v:17" *)
  DFF _313_ (
    .C(clk_4f),
    .D(_000_[7]),
    .Q(data_out_8x32[7])
  );
  (* src = "Demux_8x32.v:17" *)
  DFF _314_ (
    .C(clk_4f),
    .D(_000_[8]),
    .Q(data_out_8x32[8])
  );
  (* src = "Demux_8x32.v:17" *)
  DFF _315_ (
    .C(clk_4f),
    .D(_000_[9]),
    .Q(data_out_8x32[9])
  );
  (* src = "Demux_8x32.v:17" *)
  DFF _316_ (
    .C(clk_4f),
    .D(_000_[10]),
    .Q(data_out_8x32[10])
  );
  (* src = "Demux_8x32.v:17" *)
  DFF _317_ (
    .C(clk_4f),
    .D(_000_[11]),
    .Q(data_out_8x32[11])
  );
  (* src = "Demux_8x32.v:17" *)
  DFF _318_ (
    .C(clk_4f),
    .D(_000_[12]),
    .Q(data_out_8x32[12])
  );
  (* src = "Demux_8x32.v:17" *)
  DFF _319_ (
    .C(clk_4f),
    .D(_000_[13]),
    .Q(data_out_8x32[13])
  );
  (* src = "Demux_8x32.v:17" *)
  DFF _320_ (
    .C(clk_4f),
    .D(_000_[14]),
    .Q(data_out_8x32[14])
  );
  (* src = "Demux_8x32.v:17" *)
  DFF _321_ (
    .C(clk_4f),
    .D(_000_[15]),
    .Q(data_out_8x32[15])
  );
  (* src = "Demux_8x32.v:17" *)
  DFF _322_ (
    .C(clk_4f),
    .D(_000_[16]),
    .Q(data_out_8x32[16])
  );
  (* src = "Demux_8x32.v:17" *)
  DFF _323_ (
    .C(clk_4f),
    .D(_000_[17]),
    .Q(data_out_8x32[17])
  );
  (* src = "Demux_8x32.v:17" *)
  DFF _324_ (
    .C(clk_4f),
    .D(_000_[18]),
    .Q(data_out_8x32[18])
  );
  (* src = "Demux_8x32.v:17" *)
  DFF _325_ (
    .C(clk_4f),
    .D(_000_[19]),
    .Q(data_out_8x32[19])
  );
  (* src = "Demux_8x32.v:17" *)
  DFF _326_ (
    .C(clk_4f),
    .D(_000_[20]),
    .Q(data_out_8x32[20])
  );
  (* src = "Demux_8x32.v:17" *)
  DFF _327_ (
    .C(clk_4f),
    .D(_000_[21]),
    .Q(data_out_8x32[21])
  );
  (* src = "Demux_8x32.v:17" *)
  DFF _328_ (
    .C(clk_4f),
    .D(_000_[22]),
    .Q(data_out_8x32[22])
  );
  (* src = "Demux_8x32.v:17" *)
  DFF _329_ (
    .C(clk_4f),
    .D(_000_[23]),
    .Q(data_out_8x32[23])
  );
  (* src = "Demux_8x32.v:17" *)
  DFF _330_ (
    .C(clk_4f),
    .D(_000_[24]),
    .Q(data_out_8x32[24])
  );
  (* src = "Demux_8x32.v:17" *)
  DFF _331_ (
    .C(clk_4f),
    .D(_000_[25]),
    .Q(data_out_8x32[25])
  );
  (* src = "Demux_8x32.v:17" *)
  DFF _332_ (
    .C(clk_4f),
    .D(_000_[26]),
    .Q(data_out_8x32[26])
  );
  (* src = "Demux_8x32.v:17" *)
  DFF _333_ (
    .C(clk_4f),
    .D(_000_[27]),
    .Q(data_out_8x32[27])
  );
  (* src = "Demux_8x32.v:17" *)
  DFF _334_ (
    .C(clk_4f),
    .D(_000_[28]),
    .Q(data_out_8x32[28])
  );
  (* src = "Demux_8x32.v:17" *)
  DFF _335_ (
    .C(clk_4f),
    .D(_000_[29]),
    .Q(data_out_8x32[29])
  );
  (* src = "Demux_8x32.v:17" *)
  DFF _336_ (
    .C(clk_4f),
    .D(_000_[30]),
    .Q(data_out_8x32[30])
  );
  (* src = "Demux_8x32.v:17" *)
  DFF _337_ (
    .C(clk_4f),
    .D(_000_[31]),
    .Q(data_out_8x32[31])
  );
  (* src = "Demux_8x32.v:17" *)
  DFF _338_ (
    .C(clk_4f),
    .D(valid_in_8x32),
    .Q(valid_out_8x32)
  );
endmodule

(* top =  1  *)
(* src = "Phy_rx_Estruc.v:5" *)
module Phy_rx_Estruc(valid_outx_Estruc, data_outx_Estruc, active1_Estruc, active2_Estruc, clk_32f, clk_4f, clk, data_in_SP, data_in_SP2, reset_L);
  (* src = "Phy_rx_Estruc.v:20" *)
  wire C1;
  (* src = "Phy_rx_Estruc.v:21" *)
  wire [7:0] C2;
  (* src = "Phy_rx_Estruc.v:20" *)
  wire C3;
  (* src = "Phy_rx_Estruc.v:20" *)
  wire C4;
  (* src = "Phy_rx_Estruc.v:20" *)
  wire C5;
  (* src = "Phy_rx_Estruc.v:22" *)
  wire [7:0] C6;
  (* src = "Phy_rx_Estruc.v:23" *)
  wire [31:0] C7;
  (* src = "Phy_rx_Estruc.v:24" *)
  wire [31:0] C8;
  (* src = "Phy_rx_Estruc.v:8" *)
  output active1_Estruc;
  (* src = "Phy_rx_Estruc.v:9" *)
  output active2_Estruc;
  (* src = "Phy_rx_Estruc.v:14" *)
  input clk;
  (* src = "Phy_rx_Estruc.v:11" *)
  input clk_32f;
  (* src = "Phy_rx_Estruc.v:13" *)
  input clk_4f;
  (* src = "Phy_rx_Estruc.v:16" *)
  input data_in_SP;
  (* src = "Phy_rx_Estruc.v:17" *)
  input data_in_SP2;
  (* src = "Phy_rx_Estruc.v:7" *)
  output [31:0] data_outx_Estruc;
  (* src = "Phy_rx_Estruc.v:18" *)
  input reset_L;
  (* src = "Phy_rx_Estruc.v:6" *)
  output valid_outx_Estruc;
  (* module_not_derived = 32'd1 *)
  (* src = "Phy_rx_Estruc.v:42" *)
  Unstriping inst (
    .clk(clk),
    .data_out(data_outx_Estruc),
    .lane_in0(C7),
    .lane_in1(C8),
    .reset(reset_L),
    .valid_in0(C3),
    .valid_in1(C4),
    .valid_out(valid_outx_Estruc)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "Phy_rx_Estruc.v:27" *)
  Serial_Paralelo inst1 (
    .active(active1_Estruc),
    .clk_32f(clk_32f),
    .data_in_SP(data_in_SP),
    .data_out_SP(C2),
    .reset_L(reset_L),
    .valid_SP(C1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "Phy_rx_Estruc.v:34" *)
  Serial_Paralelo inst3 (
    .active(active2_Estruc),
    .clk_32f(clk_32f),
    .data_in_SP(data_in_SP2),
    .data_out_SP(C6),
    .reset_L(reset_L),
    .valid_SP(C5)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "Phy_rx_Estruc.v:31" *)
  Demux_8x32 ints2 (
    .clk_4f(clk_4f),
    .data_in_8x32(C2),
    .data_out_8x32(C7),
    .reset_L(reset_L),
    .valid_in_8x32(C1),
    .valid_out_8x32(C3)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "Phy_rx_Estruc.v:38" *)
  Demux_8x32 ints4 (
    .clk_4f(clk_4f),
    .data_in_8x32(C6),
    .data_out_8x32(C8),
    .reset_L(reset_L),
    .valid_in_8x32(C5),
    .valid_out_8x32(C4)
  );
endmodule

(* src = "Serial_Paralelo.v:1" *)
module Serial_Paralelo(data_out_SP, valid_SP, active, clk_32f, data_in_SP, reset_L);
  (* src = "Serial_Paralelo.v:40" *)
  wire _000_;
  (* src = "Serial_Paralelo.v:40" *)
  wire [1:0] _001_;
  (* src = "Serial_Paralelo.v:40" *)
  wire [7:0] _002_;
  (* src = "Serial_Paralelo.v:40" *)
  wire _003_;
  (* src = "Serial_Paralelo.v:40" *)
  wire [2:0] _004_;
  (* src = "Serial_Paralelo.v:40" *)
  wire [2:0] _005_;
  (* src = "Serial_Paralelo.v:40" *)
  wire [7:0] _006_;
  (* src = "Serial_Paralelo.v:40" *)
  wire [7:0] _007_;
  (* src = "Serial_Paralelo.v:40" *)
  wire [2:0] _008_;
  (* src = "Serial_Paralelo.v:40" *)
  wire [2:0] _009_;
  (* src = "Serial_Paralelo.v:40" *)
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  (* src = "Serial_Paralelo.v:18" *)
  wire Aux1;
  (* src = "Serial_Paralelo.v:4" *)
  output active;
  (* src = "Serial_Paralelo.v:5" *)
  input clk_32f;
  (* src = "Serial_Paralelo.v:11" *)
  wire [1:0] cont;
  (* src = "Serial_Paralelo.v:6" *)
  input data_in_SP;
  (* src = "Serial_Paralelo.v:2" *)
  output [7:0] data_out_SP;
  (* src = "Serial_Paralelo.v:16" *)
  wire flag2;
  (* src = "Serial_Paralelo.v:19" *)
  wire [2:0] flag3;
  (* src = "Serial_Paralelo.v:12" *)
  wire [2:0] i;
  (* src = "Serial_Paralelo.v:9" *)
  wire [7:0] inic;
  (* src = "Serial_Paralelo.v:10" *)
  wire [7:0] inic2;
  (* src = "Serial_Paralelo.v:13" *)
  wire [2:0] j;
  (* src = "Serial_Paralelo.v:14" *)
  wire [2:0] k;
  (* src = "Serial_Paralelo.v:7" *)
  input reset_L;
  (* src = "Serial_Paralelo.v:3" *)
  output valid_SP;
  NOT _273_ (
    .A(flag3[1]),
    .Y(_259_)
  );
  NOT _274_ (
    .A(inic2[6]),
    .Y(_260_)
  );
  NOT _275_ (
    .A(i[2]),
    .Y(_261_)
  );
  NOT _276_ (
    .A(i[0]),
    .Y(_262_)
  );
  NOT _277_ (
    .A(i[1]),
    .Y(_263_)
  );
  NOT _278_ (
    .A(j[2]),
    .Y(_264_)
  );
  NOT _279_ (
    .A(j[0]),
    .Y(_265_)
  );
  NOT _280_ (
    .A(j[1]),
    .Y(_266_)
  );
  NOT _281_ (
    .A(reset_L),
    .Y(_267_)
  );
  NOT _282_ (
    .A(flag3[2]),
    .Y(_268_)
  );
  NOT _283_ (
    .A(inic2[7]),
    .Y(_269_)
  );
  NOT _284_ (
    .A(data_in_SP),
    .Y(_270_)
  );
  NOT _285_ (
    .A(k[0]),
    .Y(_271_)
  );
  NOT _286_ (
    .A(k[2]),
    .Y(_272_)
  );
  NOT _287_ (
    .A(valid_SP),
    .Y(_011_)
  );
  NOT _288_ (
    .A(cont[0]),
    .Y(_012_)
  );
  NAND _289_ (
    .A(inic2[5]),
    .B(inic2[4]),
    .Y(_013_)
  );
  NAND _290_ (
    .A(inic2[3]),
    .B(inic2[2]),
    .Y(_014_)
  );
  NOR _291_ (
    .A(_013_),
    .B(_014_),
    .Y(_015_)
  );
  NOT _292_ (
    .A(_015_),
    .Y(_016_)
  );
  NOR _293_ (
    .A(inic2[0]),
    .B(inic2[1]),
    .Y(_017_)
  );
  NOT _294_ (
    .A(_017_),
    .Y(_018_)
  );
  NOR _295_ (
    .A(inic2[6]),
    .B(_269_),
    .Y(_019_)
  );
  NAND _296_ (
    .A(_260_),
    .B(inic2[7]),
    .Y(_020_)
  );
  NOR _297_ (
    .A(_018_),
    .B(_020_),
    .Y(_021_)
  );
  NAND _298_ (
    .A(_017_),
    .B(_019_),
    .Y(_022_)
  );
  NOR _299_ (
    .A(_016_),
    .B(_022_),
    .Y(_023_)
  );
  NAND _300_ (
    .A(_015_),
    .B(_021_),
    .Y(_024_)
  );
  NOR _301_ (
    .A(j[2]),
    .B(j[1]),
    .Y(_025_)
  );
  NAND _302_ (
    .A(_265_),
    .B(_025_),
    .Y(_026_)
  );
  NOR _303_ (
    .A(_024_),
    .B(_026_),
    .Y(_027_)
  );
  NAND _304_ (
    .A(flag3[0]),
    .B(_027_),
    .Y(_028_)
  );
  NOT _305_ (
    .A(_028_),
    .Y(_029_)
  );
  NAND _306_ (
    .A(flag3[1]),
    .B(_029_),
    .Y(_030_)
  );
  NOT _307_ (
    .A(_030_),
    .Y(_031_)
  );
  NAND _308_ (
    .A(_259_),
    .B(_028_),
    .Y(_032_)
  );
  NAND _309_ (
    .A(reset_L),
    .B(_032_),
    .Y(_033_)
  );
  NOR _310_ (
    .A(_031_),
    .B(_033_),
    .Y(_004_[1])
  );
  NOR _311_ (
    .A(_268_),
    .B(_030_),
    .Y(_034_)
  );
  NAND _312_ (
    .A(_268_),
    .B(_030_),
    .Y(_035_)
  );
  NAND _313_ (
    .A(reset_L),
    .B(_035_),
    .Y(_036_)
  );
  NOR _314_ (
    .A(_034_),
    .B(_036_),
    .Y(_004_[2])
  );
  NAND _315_ (
    .A(j[0]),
    .B(j[1]),
    .Y(_037_)
  );
  NOT _316_ (
    .A(_037_),
    .Y(_038_)
  );
  NAND _317_ (
    .A(j[2]),
    .B(flag3[2]),
    .Y(_039_)
  );
  NAND _318_ (
    .A(cont[0]),
    .B(cont[1]),
    .Y(_040_)
  );
  NOR _319_ (
    .A(_039_),
    .B(_040_),
    .Y(_041_)
  );
  NOT _320_ (
    .A(_041_),
    .Y(_042_)
  );
  NOR _321_ (
    .A(flag3[0]),
    .B(flag3[1]),
    .Y(_043_)
  );
  NOT _322_ (
    .A(_043_),
    .Y(_044_)
  );
  NOR _323_ (
    .A(_037_),
    .B(_044_),
    .Y(_045_)
  );
  NAND _324_ (
    .A(_038_),
    .B(_043_),
    .Y(_046_)
  );
  NOR _325_ (
    .A(_042_),
    .B(_046_),
    .Y(_047_)
  );
  NAND _326_ (
    .A(_041_),
    .B(_045_),
    .Y(_048_)
  );
  NOR _327_ (
    .A(_024_),
    .B(_048_),
    .Y(_049_)
  );
  NAND _328_ (
    .A(_023_),
    .B(_047_),
    .Y(_050_)
  );
  NAND _329_ (
    .A(reset_L),
    .B(flag2),
    .Y(_051_)
  );
  NAND _330_ (
    .A(reset_L),
    .B(data_in_SP),
    .Y(_052_)
  );
  NAND _331_ (
    .A(_270_),
    .B(_051_),
    .Y(_003_)
  );
  NAND _332_ (
    .A(reset_L),
    .B(_003_),
    .Y(_053_)
  );
  NAND _333_ (
    .A(_051_),
    .B(_052_),
    .Y(_054_)
  );
  NOR _334_ (
    .A(_049_),
    .B(_053_),
    .Y(_055_)
  );
  NAND _335_ (
    .A(_050_),
    .B(_054_),
    .Y(_056_)
  );
  NAND _336_ (
    .A(j[2]),
    .B(_055_),
    .Y(_057_)
  );
  NOR _337_ (
    .A(_037_),
    .B(_057_),
    .Y(_058_)
  );
  NAND _338_ (
    .A(data_in_SP),
    .B(_058_),
    .Y(_059_)
  );
  NAND _339_ (
    .A(reset_L),
    .B(inic2[7]),
    .Y(_060_)
  );
  NOR _340_ (
    .A(_058_),
    .B(_060_),
    .Y(_061_)
  );
  NOT _341_ (
    .A(_061_),
    .Y(_062_)
  );
  NAND _342_ (
    .A(_059_),
    .B(_062_),
    .Y(_006_[7])
  );
  NAND _343_ (
    .A(reset_L),
    .B(_049_),
    .Y(_063_)
  );
  NOT _344_ (
    .A(_063_),
    .Y(active)
  );
  NOR _345_ (
    .A(_262_),
    .B(_263_),
    .Y(_064_)
  );
  NAND _346_ (
    .A(i[0]),
    .B(i[1]),
    .Y(_065_)
  );
  NOR _347_ (
    .A(_261_),
    .B(_063_),
    .Y(_066_)
  );
  NAND _348_ (
    .A(i[2]),
    .B(active),
    .Y(_067_)
  );
  NOR _349_ (
    .A(_065_),
    .B(_067_),
    .Y(_068_)
  );
  NAND _350_ (
    .A(_064_),
    .B(_066_),
    .Y(_069_)
  );
  NOR _351_ (
    .A(_270_),
    .B(_069_),
    .Y(_070_)
  );
  NAND _352_ (
    .A(data_in_SP),
    .B(_068_),
    .Y(_071_)
  );
  NAND _353_ (
    .A(reset_L),
    .B(data_out_SP[7]),
    .Y(_072_)
  );
  NOR _354_ (
    .A(_068_),
    .B(_072_),
    .Y(_073_)
  );
  NOR _355_ (
    .A(_070_),
    .B(_073_),
    .Y(_074_)
  );
  NAND _356_ (
    .A(k[1]),
    .B(k[2]),
    .Y(_075_)
  );
  NOT _357_ (
    .A(_075_),
    .Y(_076_)
  );
  NAND _358_ (
    .A(inic[7]),
    .B(_076_),
    .Y(_077_)
  );
  NAND _359_ (
    .A(inic[4]),
    .B(inic[3]),
    .Y(_078_)
  );
  NAND _360_ (
    .A(inic[2]),
    .B(k[0]),
    .Y(_079_)
  );
  NOR _361_ (
    .A(_078_),
    .B(_079_),
    .Y(_080_)
  );
  NOT _362_ (
    .A(_080_),
    .Y(_081_)
  );
  NOR _363_ (
    .A(inic[0]),
    .B(_081_),
    .Y(_082_)
  );
  NOR _364_ (
    .A(inic[1]),
    .B(inic[6]),
    .Y(_083_)
  );
  NAND _365_ (
    .A(inic[5]),
    .B(_083_),
    .Y(_084_)
  );
  NOR _366_ (
    .A(_077_),
    .B(_084_),
    .Y(_085_)
  );
  NAND _367_ (
    .A(_082_),
    .B(_085_),
    .Y(_086_)
  );
  NOR _368_ (
    .A(_063_),
    .B(_086_),
    .Y(_087_)
  );
  NOR _369_ (
    .A(_074_),
    .B(_087_),
    .Y(_002_[7])
  );
  NOR _370_ (
    .A(_262_),
    .B(i[1]),
    .Y(_088_)
  );
  NAND _371_ (
    .A(i[0]),
    .B(_263_),
    .Y(_089_)
  );
  NOR _372_ (
    .A(_067_),
    .B(_089_),
    .Y(_090_)
  );
  NAND _373_ (
    .A(_066_),
    .B(_088_),
    .Y(_091_)
  );
  NOR _374_ (
    .A(_270_),
    .B(_091_),
    .Y(_092_)
  );
  NAND _375_ (
    .A(data_in_SP),
    .B(_090_),
    .Y(_093_)
  );
  NAND _376_ (
    .A(reset_L),
    .B(data_out_SP[5]),
    .Y(_094_)
  );
  NOR _377_ (
    .A(_090_),
    .B(_094_),
    .Y(_095_)
  );
  NOR _378_ (
    .A(_092_),
    .B(_095_),
    .Y(_096_)
  );
  NOR _379_ (
    .A(_087_),
    .B(_096_),
    .Y(_002_[5])
  );
  NOR _380_ (
    .A(i[0]),
    .B(i[1]),
    .Y(_097_)
  );
  NOT _381_ (
    .A(_097_),
    .Y(_098_)
  );
  NOR _382_ (
    .A(_067_),
    .B(_098_),
    .Y(_099_)
  );
  NAND _383_ (
    .A(_066_),
    .B(_097_),
    .Y(_100_)
  );
  NOR _384_ (
    .A(_270_),
    .B(_100_),
    .Y(_101_)
  );
  NAND _385_ (
    .A(data_in_SP),
    .B(_099_),
    .Y(_102_)
  );
  NAND _386_ (
    .A(reset_L),
    .B(data_out_SP[4]),
    .Y(_103_)
  );
  NOR _387_ (
    .A(_099_),
    .B(_103_),
    .Y(_104_)
  );
  NOR _388_ (
    .A(_101_),
    .B(_104_),
    .Y(_105_)
  );
  NOR _389_ (
    .A(_087_),
    .B(_105_),
    .Y(_002_[4])
  );
  NOR _390_ (
    .A(i[2]),
    .B(_063_),
    .Y(_106_)
  );
  NAND _391_ (
    .A(_261_),
    .B(active),
    .Y(_107_)
  );
  NOR _392_ (
    .A(_065_),
    .B(_107_),
    .Y(_108_)
  );
  NAND _393_ (
    .A(_064_),
    .B(_106_),
    .Y(_109_)
  );
  NOR _394_ (
    .A(_270_),
    .B(_109_),
    .Y(_110_)
  );
  NAND _395_ (
    .A(data_in_SP),
    .B(_108_),
    .Y(_111_)
  );
  NAND _396_ (
    .A(reset_L),
    .B(data_out_SP[3]),
    .Y(_112_)
  );
  NOR _397_ (
    .A(_108_),
    .B(_112_),
    .Y(_113_)
  );
  NOR _398_ (
    .A(_110_),
    .B(_113_),
    .Y(_114_)
  );
  NOR _399_ (
    .A(_087_),
    .B(_114_),
    .Y(_002_[3])
  );
  NOR _400_ (
    .A(i[0]),
    .B(_263_),
    .Y(_115_)
  );
  NAND _401_ (
    .A(_262_),
    .B(i[1]),
    .Y(_116_)
  );
  NOR _402_ (
    .A(_107_),
    .B(_116_),
    .Y(_117_)
  );
  NAND _403_ (
    .A(_106_),
    .B(_115_),
    .Y(_118_)
  );
  NOR _404_ (
    .A(_270_),
    .B(_118_),
    .Y(_119_)
  );
  NAND _405_ (
    .A(data_in_SP),
    .B(_117_),
    .Y(_120_)
  );
  NAND _406_ (
    .A(reset_L),
    .B(data_out_SP[2]),
    .Y(_121_)
  );
  NOR _407_ (
    .A(_117_),
    .B(_121_),
    .Y(_122_)
  );
  NOR _408_ (
    .A(_119_),
    .B(_122_),
    .Y(_123_)
  );
  NOR _409_ (
    .A(_087_),
    .B(_123_),
    .Y(_002_[2])
  );
  NOR _410_ (
    .A(_089_),
    .B(_107_),
    .Y(_124_)
  );
  NAND _411_ (
    .A(_088_),
    .B(_106_),
    .Y(_125_)
  );
  NOR _412_ (
    .A(_270_),
    .B(_125_),
    .Y(_126_)
  );
  NAND _413_ (
    .A(data_in_SP),
    .B(_124_),
    .Y(_127_)
  );
  NAND _414_ (
    .A(reset_L),
    .B(data_out_SP[1]),
    .Y(_128_)
  );
  NOR _415_ (
    .A(_124_),
    .B(_128_),
    .Y(_129_)
  );
  NOR _416_ (
    .A(_126_),
    .B(_129_),
    .Y(_130_)
  );
  NOR _417_ (
    .A(_087_),
    .B(_130_),
    .Y(_002_[1])
  );
  NAND _418_ (
    .A(_049_),
    .B(_097_),
    .Y(_131_)
  );
  NOR _419_ (
    .A(i[2]),
    .B(_131_),
    .Y(_132_)
  );
  NOR _420_ (
    .A(_267_),
    .B(_132_),
    .Y(_133_)
  );
  NOR _421_ (
    .A(_098_),
    .B(_107_),
    .Y(_134_)
  );
  NAND _422_ (
    .A(_097_),
    .B(_106_),
    .Y(_135_)
  );
  NAND _423_ (
    .A(reset_L),
    .B(data_out_SP[0]),
    .Y(_136_)
  );
  NOR _424_ (
    .A(_134_),
    .B(_136_),
    .Y(_137_)
  );
  NOR _425_ (
    .A(_270_),
    .B(_135_),
    .Y(_138_)
  );
  NAND _426_ (
    .A(data_in_SP),
    .B(_134_),
    .Y(_139_)
  );
  NOR _427_ (
    .A(_137_),
    .B(_138_),
    .Y(_140_)
  );
  NOR _428_ (
    .A(_087_),
    .B(_140_),
    .Y(_002_[0])
  );
  NOR _429_ (
    .A(_067_),
    .B(_116_),
    .Y(_141_)
  );
  NAND _430_ (
    .A(_066_),
    .B(_115_),
    .Y(_142_)
  );
  NOR _431_ (
    .A(_270_),
    .B(_142_),
    .Y(_143_)
  );
  NAND _432_ (
    .A(data_in_SP),
    .B(_141_),
    .Y(_144_)
  );
  NAND _433_ (
    .A(reset_L),
    .B(data_out_SP[6]),
    .Y(_145_)
  );
  NOR _434_ (
    .A(_141_),
    .B(_145_),
    .Y(_146_)
  );
  NOR _435_ (
    .A(_143_),
    .B(_146_),
    .Y(_147_)
  );
  NOR _436_ (
    .A(_087_),
    .B(_147_),
    .Y(_002_[6])
  );
  NAND _437_ (
    .A(inic[6]),
    .B(reset_L),
    .Y(_148_)
  );
  NOR _438_ (
    .A(_141_),
    .B(_148_),
    .Y(_149_)
  );
  NOT _439_ (
    .A(_149_),
    .Y(_150_)
  );
  NAND _440_ (
    .A(_144_),
    .B(_150_),
    .Y(_007_[6])
  );
  NAND _441_ (
    .A(reset_L),
    .B(inic[5]),
    .Y(_151_)
  );
  NOR _442_ (
    .A(_090_),
    .B(_151_),
    .Y(_152_)
  );
  NOT _443_ (
    .A(_152_),
    .Y(_153_)
  );
  NAND _444_ (
    .A(_093_),
    .B(_153_),
    .Y(_007_[5])
  );
  NAND _445_ (
    .A(reset_L),
    .B(inic[4]),
    .Y(_154_)
  );
  NOT _446_ (
    .A(_154_),
    .Y(_155_)
  );
  NAND _447_ (
    .A(_100_),
    .B(_155_),
    .Y(_156_)
  );
  NAND _448_ (
    .A(_102_),
    .B(_156_),
    .Y(_007_[4])
  );
  NAND _449_ (
    .A(reset_L),
    .B(inic[3]),
    .Y(_157_)
  );
  NOR _450_ (
    .A(_108_),
    .B(_157_),
    .Y(_158_)
  );
  NOT _451_ (
    .A(_158_),
    .Y(_159_)
  );
  NAND _452_ (
    .A(_111_),
    .B(_159_),
    .Y(_007_[3])
  );
  NAND _453_ (
    .A(reset_L),
    .B(inic[2]),
    .Y(_160_)
  );
  NOT _454_ (
    .A(_160_),
    .Y(_161_)
  );
  NAND _455_ (
    .A(_118_),
    .B(_161_),
    .Y(_162_)
  );
  NAND _456_ (
    .A(_120_),
    .B(_162_),
    .Y(_007_[2])
  );
  NAND _457_ (
    .A(inic[1]),
    .B(reset_L),
    .Y(_163_)
  );
  NOT _458_ (
    .A(_163_),
    .Y(_164_)
  );
  NAND _459_ (
    .A(_125_),
    .B(_164_),
    .Y(_165_)
  );
  NAND _460_ (
    .A(_127_),
    .B(_165_),
    .Y(_007_[1])
  );
  NAND _461_ (
    .A(inic[0]),
    .B(_133_),
    .Y(_166_)
  );
  NAND _462_ (
    .A(_139_),
    .B(_166_),
    .Y(_007_[0])
  );
  NOR _463_ (
    .A(j[0]),
    .B(_266_),
    .Y(_167_)
  );
  NAND _464_ (
    .A(_265_),
    .B(j[1]),
    .Y(_168_)
  );
  NOR _465_ (
    .A(_057_),
    .B(_168_),
    .Y(_169_)
  );
  NAND _466_ (
    .A(data_in_SP),
    .B(_169_),
    .Y(_170_)
  );
  NAND _467_ (
    .A(inic2[6]),
    .B(reset_L),
    .Y(_171_)
  );
  NOR _468_ (
    .A(_169_),
    .B(_171_),
    .Y(_172_)
  );
  NOT _469_ (
    .A(_172_),
    .Y(_173_)
  );
  NAND _470_ (
    .A(_170_),
    .B(_173_),
    .Y(_006_[6])
  );
  NOR _471_ (
    .A(_265_),
    .B(j[1]),
    .Y(_174_)
  );
  NAND _472_ (
    .A(j[0]),
    .B(_266_),
    .Y(_175_)
  );
  NOR _473_ (
    .A(_057_),
    .B(_175_),
    .Y(_176_)
  );
  NAND _474_ (
    .A(data_in_SP),
    .B(_176_),
    .Y(_177_)
  );
  NAND _475_ (
    .A(reset_L),
    .B(inic2[5]),
    .Y(_178_)
  );
  NOR _476_ (
    .A(_176_),
    .B(_178_),
    .Y(_179_)
  );
  NOT _477_ (
    .A(_179_),
    .Y(_180_)
  );
  NAND _478_ (
    .A(_177_),
    .B(_180_),
    .Y(_006_[5])
  );
  NOR _479_ (
    .A(j[0]),
    .B(_056_),
    .Y(_181_)
  );
  NAND _480_ (
    .A(_265_),
    .B(_055_),
    .Y(_182_)
  );
  NOR _481_ (
    .A(j[1]),
    .B(_182_),
    .Y(_183_)
  );
  NAND _482_ (
    .A(_266_),
    .B(_181_),
    .Y(_184_)
  );
  NOR _483_ (
    .A(_264_),
    .B(_184_),
    .Y(_185_)
  );
  NAND _484_ (
    .A(j[2]),
    .B(_183_),
    .Y(_186_)
  );
  NAND _485_ (
    .A(reset_L),
    .B(inic2[4]),
    .Y(_187_)
  );
  NOT _486_ (
    .A(_187_),
    .Y(_188_)
  );
  NAND _487_ (
    .A(_186_),
    .B(_188_),
    .Y(_189_)
  );
  NAND _488_ (
    .A(data_in_SP),
    .B(_185_),
    .Y(_190_)
  );
  NAND _489_ (
    .A(_189_),
    .B(_190_),
    .Y(_006_[4])
  );
  NOR _490_ (
    .A(j[2]),
    .B(_056_),
    .Y(_191_)
  );
  NAND _491_ (
    .A(_264_),
    .B(_055_),
    .Y(_192_)
  );
  NOR _492_ (
    .A(_037_),
    .B(_192_),
    .Y(_193_)
  );
  NAND _493_ (
    .A(data_in_SP),
    .B(_193_),
    .Y(_194_)
  );
  NAND _494_ (
    .A(reset_L),
    .B(inic2[3]),
    .Y(_195_)
  );
  NOR _495_ (
    .A(_193_),
    .B(_195_),
    .Y(_196_)
  );
  NOT _496_ (
    .A(_196_),
    .Y(_197_)
  );
  NAND _497_ (
    .A(_194_),
    .B(_197_),
    .Y(_006_[3])
  );
  NAND _498_ (
    .A(_167_),
    .B(_191_),
    .Y(_198_)
  );
  NAND _499_ (
    .A(reset_L),
    .B(inic2[2]),
    .Y(_199_)
  );
  NOR _500_ (
    .A(data_in_SP),
    .B(_198_),
    .Y(_200_)
  );
  NAND _501_ (
    .A(_198_),
    .B(_199_),
    .Y(_201_)
  );
  NOT _502_ (
    .A(_201_),
    .Y(_202_)
  );
  NOR _503_ (
    .A(_200_),
    .B(_202_),
    .Y(_006_[2])
  );
  NAND _504_ (
    .A(_174_),
    .B(_191_),
    .Y(_203_)
  );
  NAND _505_ (
    .A(inic2[1]),
    .B(reset_L),
    .Y(_204_)
  );
  NOR _506_ (
    .A(data_in_SP),
    .B(_203_),
    .Y(_205_)
  );
  NAND _507_ (
    .A(_203_),
    .B(_204_),
    .Y(_206_)
  );
  NOT _508_ (
    .A(_206_),
    .Y(_207_)
  );
  NOR _509_ (
    .A(_205_),
    .B(_207_),
    .Y(_006_[1])
  );
  NOR _510_ (
    .A(_026_),
    .B(_056_),
    .Y(_208_)
  );
  NAND _511_ (
    .A(_025_),
    .B(_181_),
    .Y(_209_)
  );
  NOR _512_ (
    .A(data_in_SP),
    .B(_209_),
    .Y(_210_)
  );
  NAND _513_ (
    .A(inic2[0]),
    .B(reset_L),
    .Y(_211_)
  );
  NOT _514_ (
    .A(_211_),
    .Y(_212_)
  );
  NOR _515_ (
    .A(_208_),
    .B(_212_),
    .Y(_213_)
  );
  NOR _516_ (
    .A(_210_),
    .B(_213_),
    .Y(_006_[0])
  );
  NAND _517_ (
    .A(reset_L),
    .B(Aux1),
    .Y(_214_)
  );
  NAND _518_ (
    .A(_063_),
    .B(_214_),
    .Y(_000_)
  );
  NAND _519_ (
    .A(_265_),
    .B(reset_L),
    .Y(_215_)
  );
  NAND _520_ (
    .A(_056_),
    .B(_215_),
    .Y(_216_)
  );
  NAND _521_ (
    .A(_182_),
    .B(_216_),
    .Y(_008_[0])
  );
  NAND _522_ (
    .A(_266_),
    .B(reset_L),
    .Y(_217_)
  );
  NAND _523_ (
    .A(_182_),
    .B(_217_),
    .Y(_218_)
  );
  NAND _524_ (
    .A(_184_),
    .B(_218_),
    .Y(_008_[1])
  );
  NAND _525_ (
    .A(_264_),
    .B(reset_L),
    .Y(_219_)
  );
  NOR _526_ (
    .A(_183_),
    .B(_219_),
    .Y(_220_)
  );
  NOR _527_ (
    .A(_185_),
    .B(_220_),
    .Y(_008_[2])
  );
  NOR _528_ (
    .A(_271_),
    .B(_050_),
    .Y(_221_)
  );
  NAND _529_ (
    .A(_271_),
    .B(_050_),
    .Y(_222_)
  );
  NAND _530_ (
    .A(reset_L),
    .B(_222_),
    .Y(_223_)
  );
  NOR _531_ (
    .A(_221_),
    .B(_223_),
    .Y(_009_[0])
  );
  NAND _532_ (
    .A(k[1]),
    .B(_221_),
    .Y(_224_)
  );
  NOT _533_ (
    .A(_224_),
    .Y(_225_)
  );
  NOR _534_ (
    .A(k[1]),
    .B(_221_),
    .Y(_226_)
  );
  NOT _535_ (
    .A(_226_),
    .Y(_227_)
  );
  NAND _536_ (
    .A(reset_L),
    .B(_227_),
    .Y(_228_)
  );
  NOR _537_ (
    .A(_225_),
    .B(_228_),
    .Y(_009_[1])
  );
  NOR _538_ (
    .A(_272_),
    .B(_224_),
    .Y(_229_)
  );
  NAND _539_ (
    .A(_272_),
    .B(_224_),
    .Y(_230_)
  );
  NAND _540_ (
    .A(reset_L),
    .B(_230_),
    .Y(_231_)
  );
  NOR _541_ (
    .A(_229_),
    .B(_231_),
    .Y(_009_[2])
  );
  NAND _542_ (
    .A(_262_),
    .B(_049_),
    .Y(_232_)
  );
  NOR _543_ (
    .A(_262_),
    .B(_049_),
    .Y(_233_)
  );
  NOR _544_ (
    .A(_267_),
    .B(_233_),
    .Y(_234_)
  );
  NAND _545_ (
    .A(_232_),
    .B(_234_),
    .Y(_005_[0])
  );
  NAND _546_ (
    .A(i[1]),
    .B(_232_),
    .Y(_235_)
  );
  NAND _547_ (
    .A(reset_L),
    .B(_235_),
    .Y(_236_)
  );
  NOT _548_ (
    .A(_236_),
    .Y(_237_)
  );
  NAND _549_ (
    .A(_131_),
    .B(_237_),
    .Y(_005_[1])
  );
  NAND _550_ (
    .A(i[2]),
    .B(_131_),
    .Y(_238_)
  );
  NAND _551_ (
    .A(_133_),
    .B(_238_),
    .Y(_005_[2])
  );
  NAND _552_ (
    .A(reset_L),
    .B(valid_SP),
    .Y(_239_)
  );
  NOT _553_ (
    .A(_239_),
    .Y(_240_)
  );
  NAND _554_ (
    .A(_050_),
    .B(_240_),
    .Y(_241_)
  );
  NAND _555_ (
    .A(Aux1),
    .B(_239_),
    .Y(_242_)
  );
  NOT _556_ (
    .A(_242_),
    .Y(_243_)
  );
  NAND _557_ (
    .A(_086_),
    .B(_243_),
    .Y(_244_)
  );
  NOR _558_ (
    .A(_011_),
    .B(_086_),
    .Y(_245_)
  );
  NOR _559_ (
    .A(_063_),
    .B(_245_),
    .Y(_246_)
  );
  NAND _560_ (
    .A(_244_),
    .B(_246_),
    .Y(_247_)
  );
  NAND _561_ (
    .A(_241_),
    .B(_247_),
    .Y(_010_)
  );
  NAND _562_ (
    .A(reset_L),
    .B(inic[7]),
    .Y(_248_)
  );
  NOR _563_ (
    .A(_068_),
    .B(_248_),
    .Y(_249_)
  );
  NOT _564_ (
    .A(_249_),
    .Y(_250_)
  );
  NAND _565_ (
    .A(_071_),
    .B(_250_),
    .Y(_007_[7])
  );
  NAND _566_ (
    .A(_012_),
    .B(_027_),
    .Y(_251_)
  );
  NOR _567_ (
    .A(_012_),
    .B(_027_),
    .Y(_252_)
  );
  NOR _568_ (
    .A(_267_),
    .B(_252_),
    .Y(_253_)
  );
  NAND _569_ (
    .A(_251_),
    .B(_253_),
    .Y(_001_[0])
  );
  NAND _570_ (
    .A(cont[1]),
    .B(_251_),
    .Y(_254_)
  );
  NOR _571_ (
    .A(cont[1]),
    .B(_251_),
    .Y(_255_)
  );
  NOR _572_ (
    .A(_267_),
    .B(_255_),
    .Y(_256_)
  );
  NAND _573_ (
    .A(_254_),
    .B(_256_),
    .Y(_001_[1])
  );
  NOR _574_ (
    .A(flag3[0]),
    .B(_027_),
    .Y(_257_)
  );
  NAND _575_ (
    .A(reset_L),
    .B(_028_),
    .Y(_258_)
  );
  NOR _576_ (
    .A(_257_),
    .B(_258_),
    .Y(_004_[0])
  );
  (* src = "Serial_Paralelo.v:40" *)
  DFF _577_ (
    .C(clk_32f),
    .D(_007_[0]),
    .Q(inic[0])
  );
  (* src = "Serial_Paralelo.v:40" *)
  DFF _578_ (
    .C(clk_32f),
    .D(_007_[1]),
    .Q(inic[1])
  );
  (* src = "Serial_Paralelo.v:40" *)
  DFF _579_ (
    .C(clk_32f),
    .D(_007_[2]),
    .Q(inic[2])
  );
  (* src = "Serial_Paralelo.v:40" *)
  DFF _580_ (
    .C(clk_32f),
    .D(_007_[3]),
    .Q(inic[3])
  );
  (* src = "Serial_Paralelo.v:40" *)
  DFF _581_ (
    .C(clk_32f),
    .D(_007_[4]),
    .Q(inic[4])
  );
  (* src = "Serial_Paralelo.v:40" *)
  DFF _582_ (
    .C(clk_32f),
    .D(_007_[5]),
    .Q(inic[5])
  );
  (* src = "Serial_Paralelo.v:40" *)
  DFF _583_ (
    .C(clk_32f),
    .D(_007_[6]),
    .Q(inic[6])
  );
  (* src = "Serial_Paralelo.v:40" *)
  DFF _584_ (
    .C(clk_32f),
    .D(_007_[7]),
    .Q(inic[7])
  );
  (* src = "Serial_Paralelo.v:40" *)
  DFF _585_ (
    .C(clk_32f),
    .D(_006_[0]),
    .Q(inic2[0])
  );
  (* src = "Serial_Paralelo.v:40" *)
  DFF _586_ (
    .C(clk_32f),
    .D(_006_[1]),
    .Q(inic2[1])
  );
  (* src = "Serial_Paralelo.v:40" *)
  DFF _587_ (
    .C(clk_32f),
    .D(_006_[2]),
    .Q(inic2[2])
  );
  (* src = "Serial_Paralelo.v:40" *)
  DFF _588_ (
    .C(clk_32f),
    .D(_006_[3]),
    .Q(inic2[3])
  );
  (* src = "Serial_Paralelo.v:40" *)
  DFF _589_ (
    .C(clk_32f),
    .D(_006_[4]),
    .Q(inic2[4])
  );
  (* src = "Serial_Paralelo.v:40" *)
  DFF _590_ (
    .C(clk_32f),
    .D(_006_[5]),
    .Q(inic2[5])
  );
  (* src = "Serial_Paralelo.v:40" *)
  DFF _591_ (
    .C(clk_32f),
    .D(_006_[6]),
    .Q(inic2[6])
  );
  (* src = "Serial_Paralelo.v:40" *)
  DFF _592_ (
    .C(clk_32f),
    .D(_006_[7]),
    .Q(inic2[7])
  );
  (* src = "Serial_Paralelo.v:40" *)
  DFF _593_ (
    .C(clk_32f),
    .D(_001_[0]),
    .Q(cont[0])
  );
  (* src = "Serial_Paralelo.v:40" *)
  DFF _594_ (
    .C(clk_32f),
    .D(_001_[1]),
    .Q(cont[1])
  );
  (* src = "Serial_Paralelo.v:40" *)
  DFF _595_ (
    .C(clk_32f),
    .D(_002_[0]),
    .Q(data_out_SP[0])
  );
  (* src = "Serial_Paralelo.v:40" *)
  DFF _596_ (
    .C(clk_32f),
    .D(_002_[1]),
    .Q(data_out_SP[1])
  );
  (* src = "Serial_Paralelo.v:40" *)
  DFF _597_ (
    .C(clk_32f),
    .D(_002_[2]),
    .Q(data_out_SP[2])
  );
  (* src = "Serial_Paralelo.v:40" *)
  DFF _598_ (
    .C(clk_32f),
    .D(_002_[3]),
    .Q(data_out_SP[3])
  );
  (* src = "Serial_Paralelo.v:40" *)
  DFF _599_ (
    .C(clk_32f),
    .D(_002_[4]),
    .Q(data_out_SP[4])
  );
  (* src = "Serial_Paralelo.v:40" *)
  DFF _600_ (
    .C(clk_32f),
    .D(_002_[5]),
    .Q(data_out_SP[5])
  );
  (* src = "Serial_Paralelo.v:40" *)
  DFF _601_ (
    .C(clk_32f),
    .D(_002_[6]),
    .Q(data_out_SP[6])
  );
  (* src = "Serial_Paralelo.v:40" *)
  DFF _602_ (
    .C(clk_32f),
    .D(_002_[7]),
    .Q(data_out_SP[7])
  );
  (* src = "Serial_Paralelo.v:40" *)
  DFF _603_ (
    .C(clk_32f),
    .D(_010_),
    .Q(valid_SP)
  );
  (* src = "Serial_Paralelo.v:40" *)
  DFF _604_ (
    .C(clk_32f),
    .D(_005_[0]),
    .Q(i[0])
  );
  (* src = "Serial_Paralelo.v:40" *)
  DFF _605_ (
    .C(clk_32f),
    .D(_005_[1]),
    .Q(i[1])
  );
  (* src = "Serial_Paralelo.v:40" *)
  DFF _606_ (
    .C(clk_32f),
    .D(_005_[2]),
    .Q(i[2])
  );
  (* src = "Serial_Paralelo.v:40" *)
  DFF _607_ (
    .C(clk_32f),
    .D(_008_[0]),
    .Q(j[0])
  );
  (* src = "Serial_Paralelo.v:40" *)
  DFF _608_ (
    .C(clk_32f),
    .D(_008_[1]),
    .Q(j[1])
  );
  (* src = "Serial_Paralelo.v:40" *)
  DFF _609_ (
    .C(clk_32f),
    .D(_008_[2]),
    .Q(j[2])
  );
  (* src = "Serial_Paralelo.v:40" *)
  DFF _610_ (
    .C(clk_32f),
    .D(_009_[0]),
    .Q(k[0])
  );
  (* src = "Serial_Paralelo.v:40" *)
  DFF _611_ (
    .C(clk_32f),
    .D(_009_[1]),
    .Q(k[1])
  );
  (* src = "Serial_Paralelo.v:40" *)
  DFF _612_ (
    .C(clk_32f),
    .D(_009_[2]),
    .Q(k[2])
  );
  (* src = "Serial_Paralelo.v:40" *)
  DFF _613_ (
    .C(clk_32f),
    .D(_003_),
    .Q(flag2)
  );
  (* src = "Serial_Paralelo.v:40" *)
  DFF _614_ (
    .C(clk_32f),
    .D(_000_),
    .Q(Aux1)
  );
  (* src = "Serial_Paralelo.v:40" *)
  DFF _615_ (
    .C(clk_32f),
    .D(_004_[0]),
    .Q(flag3[0])
  );
  (* src = "Serial_Paralelo.v:40" *)
  DFF _616_ (
    .C(clk_32f),
    .D(_004_[1]),
    .Q(flag3[1])
  );
  (* src = "Serial_Paralelo.v:40" *)
  DFF _617_ (
    .C(clk_32f),
    .D(_004_[2]),
    .Q(flag3[2])
  );
endmodule

(* src = "Unstriping.v:1" *)
module Unstriping(clk, data_out, valid_out, valid_in0, valid_in1, reset, lane_in0, lane_in1);
  (* src = "Unstriping.v:49" *)
  wire [31:0] _000_;
  (* src = "Unstriping.v:49" *)
  wire _001_;
  (* src = "Unstriping.v:49" *)
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  (* src = "Unstriping.v:2" *)
  input clk;
  (* src = "Unstriping.v:3" *)
  output [31:0] data_out;
  (* src = "Unstriping.v:13" *)
  wire [31:0] lane0;
  (* src = "Unstriping.v:8" *)
  input [31:0] lane_in0;
  (* src = "Unstriping.v:9" *)
  input [31:0] lane_in1;
  (* src = "Unstriping.v:7" *)
  input reset;
  (* src = "Unstriping.v:12" *)
  wire selector;
  (* src = "Unstriping.v:11" *)
  wire valid0;
  (* src = "Unstriping.v:11" *)
  wire valid1;
  (* src = "Unstriping.v:5" *)
  input valid_in0;
  (* src = "Unstriping.v:6" *)
  input valid_in1;
  (* src = "Unstriping.v:4" *)
  output valid_out;
  NOT _265_ (
    .A(valid_out),
    .Y(_003_)
  );
  NOT _266_ (
    .A(data_out[0]),
    .Y(_004_)
  );
  NOT _267_ (
    .A(data_out[1]),
    .Y(_005_)
  );
  NOT _268_ (
    .A(data_out[2]),
    .Y(_006_)
  );
  NOT _269_ (
    .A(data_out[3]),
    .Y(_007_)
  );
  NOT _270_ (
    .A(data_out[4]),
    .Y(_008_)
  );
  NOT _271_ (
    .A(data_out[5]),
    .Y(_009_)
  );
  NOT _272_ (
    .A(data_out[6]),
    .Y(_010_)
  );
  NOT _273_ (
    .A(data_out[7]),
    .Y(_011_)
  );
  NOT _274_ (
    .A(data_out[8]),
    .Y(_012_)
  );
  NOT _275_ (
    .A(data_out[9]),
    .Y(_013_)
  );
  NOT _276_ (
    .A(data_out[10]),
    .Y(_014_)
  );
  NOT _277_ (
    .A(data_out[11]),
    .Y(_015_)
  );
  NOT _278_ (
    .A(data_out[12]),
    .Y(_016_)
  );
  NOT _279_ (
    .A(data_out[13]),
    .Y(_017_)
  );
  NOT _280_ (
    .A(data_out[14]),
    .Y(_018_)
  );
  NOT _281_ (
    .A(data_out[15]),
    .Y(_019_)
  );
  NOT _282_ (
    .A(data_out[16]),
    .Y(_020_)
  );
  NOT _283_ (
    .A(data_out[17]),
    .Y(_021_)
  );
  NOT _284_ (
    .A(data_out[18]),
    .Y(_022_)
  );
  NOT _285_ (
    .A(data_out[19]),
    .Y(_023_)
  );
  NOT _286_ (
    .A(data_out[20]),
    .Y(_024_)
  );
  NOT _287_ (
    .A(data_out[21]),
    .Y(_025_)
  );
  NOT _288_ (
    .A(data_out[22]),
    .Y(_026_)
  );
  NOT _289_ (
    .A(data_out[23]),
    .Y(_027_)
  );
  NOT _290_ (
    .A(data_out[24]),
    .Y(_028_)
  );
  NOT _291_ (
    .A(data_out[25]),
    .Y(_029_)
  );
  NOT _292_ (
    .A(data_out[26]),
    .Y(_030_)
  );
  NOT _293_ (
    .A(data_out[27]),
    .Y(_031_)
  );
  NOT _294_ (
    .A(data_out[28]),
    .Y(_032_)
  );
  NOT _295_ (
    .A(data_out[29]),
    .Y(_033_)
  );
  NOT _296_ (
    .A(data_out[30]),
    .Y(_034_)
  );
  NOT _297_ (
    .A(data_out[31]),
    .Y(_035_)
  );
  NAND _298_ (
    .A(selector),
    .B(valid_in1),
    .Y(_036_)
  );
  NOT _299_ (
    .A(_036_),
    .Y(_037_)
  );
  NAND _300_ (
    .A(valid_in0),
    .B(reset),
    .Y(_038_)
  );
  NOR _301_ (
    .A(_037_),
    .B(_038_),
    .Y(_001_)
  );
  NAND _302_ (
    .A(selector),
    .B(_003_),
    .Y(_039_)
  );
  NOR _303_ (
    .A(valid_in1),
    .B(_039_),
    .Y(_040_)
  );
  NOR _304_ (
    .A(_038_),
    .B(_040_),
    .Y(_002_)
  );
  NAND _305_ (
    .A(valid_in1),
    .B(lane_in1[0]),
    .Y(_041_)
  );
  NOR _306_ (
    .A(valid_in1),
    .B(_004_),
    .Y(_042_)
  );
  NAND _307_ (
    .A(selector),
    .B(_041_),
    .Y(_043_)
  );
  NOR _308_ (
    .A(_042_),
    .B(_043_),
    .Y(_044_)
  );
  NOR _309_ (
    .A(selector),
    .B(lane_in0[0]),
    .Y(_045_)
  );
  NOR _310_ (
    .A(_038_),
    .B(_045_),
    .Y(_046_)
  );
  NOT _311_ (
    .A(_046_),
    .Y(_047_)
  );
  NOR _312_ (
    .A(_044_),
    .B(_047_),
    .Y(_000_[0])
  );
  NAND _313_ (
    .A(valid_in1),
    .B(lane_in1[1]),
    .Y(_048_)
  );
  NOR _314_ (
    .A(valid_in1),
    .B(_005_),
    .Y(_049_)
  );
  NAND _315_ (
    .A(selector),
    .B(_048_),
    .Y(_050_)
  );
  NOR _316_ (
    .A(_049_),
    .B(_050_),
    .Y(_051_)
  );
  NOR _317_ (
    .A(selector),
    .B(lane_in0[1]),
    .Y(_052_)
  );
  NOR _318_ (
    .A(_038_),
    .B(_052_),
    .Y(_053_)
  );
  NOT _319_ (
    .A(_053_),
    .Y(_054_)
  );
  NOR _320_ (
    .A(_051_),
    .B(_054_),
    .Y(_000_[1])
  );
  NAND _321_ (
    .A(valid_in1),
    .B(lane_in1[2]),
    .Y(_055_)
  );
  NOR _322_ (
    .A(valid_in1),
    .B(_006_),
    .Y(_056_)
  );
  NAND _323_ (
    .A(selector),
    .B(_055_),
    .Y(_057_)
  );
  NOR _324_ (
    .A(_056_),
    .B(_057_),
    .Y(_058_)
  );
  NOR _325_ (
    .A(selector),
    .B(lane_in0[2]),
    .Y(_059_)
  );
  NOR _326_ (
    .A(_038_),
    .B(_059_),
    .Y(_060_)
  );
  NOT _327_ (
    .A(_060_),
    .Y(_061_)
  );
  NOR _328_ (
    .A(_058_),
    .B(_061_),
    .Y(_000_[2])
  );
  NAND _329_ (
    .A(valid_in1),
    .B(lane_in1[3]),
    .Y(_062_)
  );
  NOR _330_ (
    .A(valid_in1),
    .B(_007_),
    .Y(_063_)
  );
  NAND _331_ (
    .A(selector),
    .B(_062_),
    .Y(_064_)
  );
  NOR _332_ (
    .A(_063_),
    .B(_064_),
    .Y(_065_)
  );
  NOR _333_ (
    .A(selector),
    .B(lane_in0[3]),
    .Y(_066_)
  );
  NOR _334_ (
    .A(_038_),
    .B(_066_),
    .Y(_067_)
  );
  NOT _335_ (
    .A(_067_),
    .Y(_068_)
  );
  NOR _336_ (
    .A(_065_),
    .B(_068_),
    .Y(_000_[3])
  );
  NAND _337_ (
    .A(valid_in1),
    .B(lane_in1[4]),
    .Y(_069_)
  );
  NOR _338_ (
    .A(valid_in1),
    .B(_008_),
    .Y(_070_)
  );
  NAND _339_ (
    .A(selector),
    .B(_069_),
    .Y(_071_)
  );
  NOR _340_ (
    .A(_070_),
    .B(_071_),
    .Y(_072_)
  );
  NOR _341_ (
    .A(selector),
    .B(lane_in0[4]),
    .Y(_073_)
  );
  NOR _342_ (
    .A(_038_),
    .B(_073_),
    .Y(_074_)
  );
  NOT _343_ (
    .A(_074_),
    .Y(_075_)
  );
  NOR _344_ (
    .A(_072_),
    .B(_075_),
    .Y(_000_[4])
  );
  NAND _345_ (
    .A(valid_in1),
    .B(lane_in1[5]),
    .Y(_076_)
  );
  NOR _346_ (
    .A(valid_in1),
    .B(_009_),
    .Y(_077_)
  );
  NAND _347_ (
    .A(selector),
    .B(_076_),
    .Y(_078_)
  );
  NOR _348_ (
    .A(_077_),
    .B(_078_),
    .Y(_079_)
  );
  NOR _349_ (
    .A(selector),
    .B(lane_in0[5]),
    .Y(_080_)
  );
  NOR _350_ (
    .A(_038_),
    .B(_080_),
    .Y(_081_)
  );
  NOT _351_ (
    .A(_081_),
    .Y(_082_)
  );
  NOR _352_ (
    .A(_079_),
    .B(_082_),
    .Y(_000_[5])
  );
  NAND _353_ (
    .A(valid_in1),
    .B(lane_in1[6]),
    .Y(_083_)
  );
  NOR _354_ (
    .A(valid_in1),
    .B(_010_),
    .Y(_084_)
  );
  NAND _355_ (
    .A(selector),
    .B(_083_),
    .Y(_085_)
  );
  NOR _356_ (
    .A(_084_),
    .B(_085_),
    .Y(_086_)
  );
  NOR _357_ (
    .A(selector),
    .B(lane_in0[6]),
    .Y(_087_)
  );
  NOR _358_ (
    .A(_038_),
    .B(_087_),
    .Y(_088_)
  );
  NOT _359_ (
    .A(_088_),
    .Y(_089_)
  );
  NOR _360_ (
    .A(_086_),
    .B(_089_),
    .Y(_000_[6])
  );
  NAND _361_ (
    .A(valid_in1),
    .B(lane_in1[7]),
    .Y(_090_)
  );
  NOR _362_ (
    .A(valid_in1),
    .B(_011_),
    .Y(_091_)
  );
  NAND _363_ (
    .A(selector),
    .B(_090_),
    .Y(_092_)
  );
  NOR _364_ (
    .A(_091_),
    .B(_092_),
    .Y(_093_)
  );
  NOR _365_ (
    .A(selector),
    .B(lane_in0[7]),
    .Y(_094_)
  );
  NOR _366_ (
    .A(_038_),
    .B(_094_),
    .Y(_095_)
  );
  NOT _367_ (
    .A(_095_),
    .Y(_096_)
  );
  NOR _368_ (
    .A(_093_),
    .B(_096_),
    .Y(_000_[7])
  );
  NAND _369_ (
    .A(valid_in1),
    .B(lane_in1[8]),
    .Y(_097_)
  );
  NOR _370_ (
    .A(valid_in1),
    .B(_012_),
    .Y(_098_)
  );
  NAND _371_ (
    .A(selector),
    .B(_097_),
    .Y(_099_)
  );
  NOR _372_ (
    .A(_098_),
    .B(_099_),
    .Y(_100_)
  );
  NOR _373_ (
    .A(selector),
    .B(lane_in0[8]),
    .Y(_101_)
  );
  NOR _374_ (
    .A(_038_),
    .B(_101_),
    .Y(_102_)
  );
  NOT _375_ (
    .A(_102_),
    .Y(_103_)
  );
  NOR _376_ (
    .A(_100_),
    .B(_103_),
    .Y(_000_[8])
  );
  NAND _377_ (
    .A(valid_in1),
    .B(lane_in1[9]),
    .Y(_104_)
  );
  NOR _378_ (
    .A(valid_in1),
    .B(_013_),
    .Y(_105_)
  );
  NAND _379_ (
    .A(selector),
    .B(_104_),
    .Y(_106_)
  );
  NOR _380_ (
    .A(_105_),
    .B(_106_),
    .Y(_107_)
  );
  NOR _381_ (
    .A(selector),
    .B(lane_in0[9]),
    .Y(_108_)
  );
  NOR _382_ (
    .A(_038_),
    .B(_108_),
    .Y(_109_)
  );
  NOT _383_ (
    .A(_109_),
    .Y(_110_)
  );
  NOR _384_ (
    .A(_107_),
    .B(_110_),
    .Y(_000_[9])
  );
  NAND _385_ (
    .A(valid_in1),
    .B(lane_in1[10]),
    .Y(_111_)
  );
  NOR _386_ (
    .A(valid_in1),
    .B(_014_),
    .Y(_112_)
  );
  NAND _387_ (
    .A(selector),
    .B(_111_),
    .Y(_113_)
  );
  NOR _388_ (
    .A(_112_),
    .B(_113_),
    .Y(_114_)
  );
  NOR _389_ (
    .A(selector),
    .B(lane_in0[10]),
    .Y(_115_)
  );
  NOR _390_ (
    .A(_038_),
    .B(_115_),
    .Y(_116_)
  );
  NOT _391_ (
    .A(_116_),
    .Y(_117_)
  );
  NOR _392_ (
    .A(_114_),
    .B(_117_),
    .Y(_000_[10])
  );
  NAND _393_ (
    .A(valid_in1),
    .B(lane_in1[11]),
    .Y(_118_)
  );
  NOR _394_ (
    .A(valid_in1),
    .B(_015_),
    .Y(_119_)
  );
  NAND _395_ (
    .A(selector),
    .B(_118_),
    .Y(_120_)
  );
  NOR _396_ (
    .A(_119_),
    .B(_120_),
    .Y(_121_)
  );
  NOR _397_ (
    .A(selector),
    .B(lane_in0[11]),
    .Y(_122_)
  );
  NOR _398_ (
    .A(_038_),
    .B(_122_),
    .Y(_123_)
  );
  NOT _399_ (
    .A(_123_),
    .Y(_124_)
  );
  NOR _400_ (
    .A(_121_),
    .B(_124_),
    .Y(_000_[11])
  );
  NAND _401_ (
    .A(valid_in1),
    .B(lane_in1[12]),
    .Y(_125_)
  );
  NOR _402_ (
    .A(valid_in1),
    .B(_016_),
    .Y(_126_)
  );
  NAND _403_ (
    .A(selector),
    .B(_125_),
    .Y(_127_)
  );
  NOR _404_ (
    .A(_126_),
    .B(_127_),
    .Y(_128_)
  );
  NOR _405_ (
    .A(selector),
    .B(lane_in0[12]),
    .Y(_129_)
  );
  NOR _406_ (
    .A(_038_),
    .B(_129_),
    .Y(_130_)
  );
  NOT _407_ (
    .A(_130_),
    .Y(_131_)
  );
  NOR _408_ (
    .A(_128_),
    .B(_131_),
    .Y(_000_[12])
  );
  NAND _409_ (
    .A(valid_in1),
    .B(lane_in1[13]),
    .Y(_132_)
  );
  NOR _410_ (
    .A(valid_in1),
    .B(_017_),
    .Y(_133_)
  );
  NAND _411_ (
    .A(selector),
    .B(_132_),
    .Y(_134_)
  );
  NOR _412_ (
    .A(_133_),
    .B(_134_),
    .Y(_135_)
  );
  NOR _413_ (
    .A(selector),
    .B(lane_in0[13]),
    .Y(_136_)
  );
  NOR _414_ (
    .A(_038_),
    .B(_136_),
    .Y(_137_)
  );
  NOT _415_ (
    .A(_137_),
    .Y(_138_)
  );
  NOR _416_ (
    .A(_135_),
    .B(_138_),
    .Y(_000_[13])
  );
  NAND _417_ (
    .A(valid_in1),
    .B(lane_in1[14]),
    .Y(_139_)
  );
  NOR _418_ (
    .A(valid_in1),
    .B(_018_),
    .Y(_140_)
  );
  NAND _419_ (
    .A(selector),
    .B(_139_),
    .Y(_141_)
  );
  NOR _420_ (
    .A(_140_),
    .B(_141_),
    .Y(_142_)
  );
  NOR _421_ (
    .A(selector),
    .B(lane_in0[14]),
    .Y(_143_)
  );
  NOR _422_ (
    .A(_038_),
    .B(_143_),
    .Y(_144_)
  );
  NOT _423_ (
    .A(_144_),
    .Y(_145_)
  );
  NOR _424_ (
    .A(_142_),
    .B(_145_),
    .Y(_000_[14])
  );
  NAND _425_ (
    .A(valid_in1),
    .B(lane_in1[15]),
    .Y(_146_)
  );
  NOR _426_ (
    .A(valid_in1),
    .B(_019_),
    .Y(_147_)
  );
  NAND _427_ (
    .A(selector),
    .B(_146_),
    .Y(_148_)
  );
  NOR _428_ (
    .A(_147_),
    .B(_148_),
    .Y(_149_)
  );
  NOR _429_ (
    .A(selector),
    .B(lane_in0[15]),
    .Y(_150_)
  );
  NOR _430_ (
    .A(_038_),
    .B(_150_),
    .Y(_151_)
  );
  NOT _431_ (
    .A(_151_),
    .Y(_152_)
  );
  NOR _432_ (
    .A(_149_),
    .B(_152_),
    .Y(_000_[15])
  );
  NAND _433_ (
    .A(valid_in1),
    .B(lane_in1[16]),
    .Y(_153_)
  );
  NOR _434_ (
    .A(valid_in1),
    .B(_020_),
    .Y(_154_)
  );
  NAND _435_ (
    .A(selector),
    .B(_153_),
    .Y(_155_)
  );
  NOR _436_ (
    .A(_154_),
    .B(_155_),
    .Y(_156_)
  );
  NOR _437_ (
    .A(selector),
    .B(lane_in0[16]),
    .Y(_157_)
  );
  NOR _438_ (
    .A(_038_),
    .B(_157_),
    .Y(_158_)
  );
  NOT _439_ (
    .A(_158_),
    .Y(_159_)
  );
  NOR _440_ (
    .A(_156_),
    .B(_159_),
    .Y(_000_[16])
  );
  NAND _441_ (
    .A(valid_in1),
    .B(lane_in1[17]),
    .Y(_160_)
  );
  NOR _442_ (
    .A(valid_in1),
    .B(_021_),
    .Y(_161_)
  );
  NAND _443_ (
    .A(selector),
    .B(_160_),
    .Y(_162_)
  );
  NOR _444_ (
    .A(_161_),
    .B(_162_),
    .Y(_163_)
  );
  NOR _445_ (
    .A(selector),
    .B(lane_in0[17]),
    .Y(_164_)
  );
  NOR _446_ (
    .A(_038_),
    .B(_164_),
    .Y(_165_)
  );
  NOT _447_ (
    .A(_165_),
    .Y(_166_)
  );
  NOR _448_ (
    .A(_163_),
    .B(_166_),
    .Y(_000_[17])
  );
  NAND _449_ (
    .A(valid_in1),
    .B(lane_in1[18]),
    .Y(_167_)
  );
  NOR _450_ (
    .A(valid_in1),
    .B(_022_),
    .Y(_168_)
  );
  NAND _451_ (
    .A(selector),
    .B(_167_),
    .Y(_169_)
  );
  NOR _452_ (
    .A(_168_),
    .B(_169_),
    .Y(_170_)
  );
  NOR _453_ (
    .A(selector),
    .B(lane_in0[18]),
    .Y(_171_)
  );
  NOR _454_ (
    .A(_038_),
    .B(_171_),
    .Y(_172_)
  );
  NOT _455_ (
    .A(_172_),
    .Y(_173_)
  );
  NOR _456_ (
    .A(_170_),
    .B(_173_),
    .Y(_000_[18])
  );
  NAND _457_ (
    .A(valid_in1),
    .B(lane_in1[19]),
    .Y(_174_)
  );
  NOR _458_ (
    .A(valid_in1),
    .B(_023_),
    .Y(_175_)
  );
  NAND _459_ (
    .A(selector),
    .B(_174_),
    .Y(_176_)
  );
  NOR _460_ (
    .A(_175_),
    .B(_176_),
    .Y(_177_)
  );
  NOR _461_ (
    .A(selector),
    .B(lane_in0[19]),
    .Y(_178_)
  );
  NOR _462_ (
    .A(_038_),
    .B(_178_),
    .Y(_179_)
  );
  NOT _463_ (
    .A(_179_),
    .Y(_180_)
  );
  NOR _464_ (
    .A(_177_),
    .B(_180_),
    .Y(_000_[19])
  );
  NAND _465_ (
    .A(valid_in1),
    .B(lane_in1[20]),
    .Y(_181_)
  );
  NOR _466_ (
    .A(valid_in1),
    .B(_024_),
    .Y(_182_)
  );
  NAND _467_ (
    .A(selector),
    .B(_181_),
    .Y(_183_)
  );
  NOR _468_ (
    .A(_182_),
    .B(_183_),
    .Y(_184_)
  );
  NOR _469_ (
    .A(selector),
    .B(lane_in0[20]),
    .Y(_185_)
  );
  NOR _470_ (
    .A(_038_),
    .B(_185_),
    .Y(_186_)
  );
  NOT _471_ (
    .A(_186_),
    .Y(_187_)
  );
  NOR _472_ (
    .A(_184_),
    .B(_187_),
    .Y(_000_[20])
  );
  NAND _473_ (
    .A(valid_in1),
    .B(lane_in1[21]),
    .Y(_188_)
  );
  NOR _474_ (
    .A(valid_in1),
    .B(_025_),
    .Y(_189_)
  );
  NAND _475_ (
    .A(selector),
    .B(_188_),
    .Y(_190_)
  );
  NOR _476_ (
    .A(_189_),
    .B(_190_),
    .Y(_191_)
  );
  NOR _477_ (
    .A(selector),
    .B(lane_in0[21]),
    .Y(_192_)
  );
  NOR _478_ (
    .A(_038_),
    .B(_192_),
    .Y(_193_)
  );
  NOT _479_ (
    .A(_193_),
    .Y(_194_)
  );
  NOR _480_ (
    .A(_191_),
    .B(_194_),
    .Y(_000_[21])
  );
  NAND _481_ (
    .A(valid_in1),
    .B(lane_in1[22]),
    .Y(_195_)
  );
  NOR _482_ (
    .A(valid_in1),
    .B(_026_),
    .Y(_196_)
  );
  NAND _483_ (
    .A(selector),
    .B(_195_),
    .Y(_197_)
  );
  NOR _484_ (
    .A(_196_),
    .B(_197_),
    .Y(_198_)
  );
  NOR _485_ (
    .A(selector),
    .B(lane_in0[22]),
    .Y(_199_)
  );
  NOR _486_ (
    .A(_038_),
    .B(_199_),
    .Y(_200_)
  );
  NOT _487_ (
    .A(_200_),
    .Y(_201_)
  );
  NOR _488_ (
    .A(_198_),
    .B(_201_),
    .Y(_000_[22])
  );
  NAND _489_ (
    .A(valid_in1),
    .B(lane_in1[23]),
    .Y(_202_)
  );
  NOR _490_ (
    .A(valid_in1),
    .B(_027_),
    .Y(_203_)
  );
  NAND _491_ (
    .A(selector),
    .B(_202_),
    .Y(_204_)
  );
  NOR _492_ (
    .A(_203_),
    .B(_204_),
    .Y(_205_)
  );
  NOR _493_ (
    .A(selector),
    .B(lane_in0[23]),
    .Y(_206_)
  );
  NOR _494_ (
    .A(_038_),
    .B(_206_),
    .Y(_207_)
  );
  NOT _495_ (
    .A(_207_),
    .Y(_208_)
  );
  NOR _496_ (
    .A(_205_),
    .B(_208_),
    .Y(_000_[23])
  );
  NAND _497_ (
    .A(valid_in1),
    .B(lane_in1[24]),
    .Y(_209_)
  );
  NOR _498_ (
    .A(valid_in1),
    .B(_028_),
    .Y(_210_)
  );
  NAND _499_ (
    .A(selector),
    .B(_209_),
    .Y(_211_)
  );
  NOR _500_ (
    .A(_210_),
    .B(_211_),
    .Y(_212_)
  );
  NOR _501_ (
    .A(selector),
    .B(lane_in0[24]),
    .Y(_213_)
  );
  NOR _502_ (
    .A(_038_),
    .B(_213_),
    .Y(_214_)
  );
  NOT _503_ (
    .A(_214_),
    .Y(_215_)
  );
  NOR _504_ (
    .A(_212_),
    .B(_215_),
    .Y(_000_[24])
  );
  NAND _505_ (
    .A(valid_in1),
    .B(lane_in1[25]),
    .Y(_216_)
  );
  NOR _506_ (
    .A(valid_in1),
    .B(_029_),
    .Y(_217_)
  );
  NAND _507_ (
    .A(selector),
    .B(_216_),
    .Y(_218_)
  );
  NOR _508_ (
    .A(_217_),
    .B(_218_),
    .Y(_219_)
  );
  NOR _509_ (
    .A(selector),
    .B(lane_in0[25]),
    .Y(_220_)
  );
  NOR _510_ (
    .A(_038_),
    .B(_220_),
    .Y(_221_)
  );
  NOT _511_ (
    .A(_221_),
    .Y(_222_)
  );
  NOR _512_ (
    .A(_219_),
    .B(_222_),
    .Y(_000_[25])
  );
  NAND _513_ (
    .A(valid_in1),
    .B(lane_in1[26]),
    .Y(_223_)
  );
  NOR _514_ (
    .A(valid_in1),
    .B(_030_),
    .Y(_224_)
  );
  NAND _515_ (
    .A(selector),
    .B(_223_),
    .Y(_225_)
  );
  NOR _516_ (
    .A(_224_),
    .B(_225_),
    .Y(_226_)
  );
  NOR _517_ (
    .A(selector),
    .B(lane_in0[26]),
    .Y(_227_)
  );
  NOR _518_ (
    .A(_038_),
    .B(_227_),
    .Y(_228_)
  );
  NOT _519_ (
    .A(_228_),
    .Y(_229_)
  );
  NOR _520_ (
    .A(_226_),
    .B(_229_),
    .Y(_000_[26])
  );
  NAND _521_ (
    .A(valid_in1),
    .B(lane_in1[27]),
    .Y(_230_)
  );
  NOR _522_ (
    .A(valid_in1),
    .B(_031_),
    .Y(_231_)
  );
  NAND _523_ (
    .A(selector),
    .B(_230_),
    .Y(_232_)
  );
  NOR _524_ (
    .A(_231_),
    .B(_232_),
    .Y(_233_)
  );
  NOR _525_ (
    .A(selector),
    .B(lane_in0[27]),
    .Y(_234_)
  );
  NOR _526_ (
    .A(_038_),
    .B(_234_),
    .Y(_235_)
  );
  NOT _527_ (
    .A(_235_),
    .Y(_236_)
  );
  NOR _528_ (
    .A(_233_),
    .B(_236_),
    .Y(_000_[27])
  );
  NAND _529_ (
    .A(valid_in1),
    .B(lane_in1[28]),
    .Y(_237_)
  );
  NOR _530_ (
    .A(valid_in1),
    .B(_032_),
    .Y(_238_)
  );
  NAND _531_ (
    .A(selector),
    .B(_237_),
    .Y(_239_)
  );
  NOR _532_ (
    .A(_238_),
    .B(_239_),
    .Y(_240_)
  );
  NOR _533_ (
    .A(selector),
    .B(lane_in0[28]),
    .Y(_241_)
  );
  NOR _534_ (
    .A(_038_),
    .B(_241_),
    .Y(_242_)
  );
  NOT _535_ (
    .A(_242_),
    .Y(_243_)
  );
  NOR _536_ (
    .A(_240_),
    .B(_243_),
    .Y(_000_[28])
  );
  NAND _537_ (
    .A(valid_in1),
    .B(lane_in1[29]),
    .Y(_244_)
  );
  NOR _538_ (
    .A(valid_in1),
    .B(_033_),
    .Y(_245_)
  );
  NAND _539_ (
    .A(selector),
    .B(_244_),
    .Y(_246_)
  );
  NOR _540_ (
    .A(_245_),
    .B(_246_),
    .Y(_247_)
  );
  NOR _541_ (
    .A(selector),
    .B(lane_in0[29]),
    .Y(_248_)
  );
  NOR _542_ (
    .A(_038_),
    .B(_248_),
    .Y(_249_)
  );
  NOT _543_ (
    .A(_249_),
    .Y(_250_)
  );
  NOR _544_ (
    .A(_247_),
    .B(_250_),
    .Y(_000_[29])
  );
  NAND _545_ (
    .A(valid_in1),
    .B(lane_in1[30]),
    .Y(_251_)
  );
  NOR _546_ (
    .A(valid_in1),
    .B(_034_),
    .Y(_252_)
  );
  NAND _547_ (
    .A(selector),
    .B(_251_),
    .Y(_253_)
  );
  NOR _548_ (
    .A(_252_),
    .B(_253_),
    .Y(_254_)
  );
  NOR _549_ (
    .A(selector),
    .B(lane_in0[30]),
    .Y(_255_)
  );
  NOR _550_ (
    .A(_038_),
    .B(_255_),
    .Y(_256_)
  );
  NOT _551_ (
    .A(_256_),
    .Y(_257_)
  );
  NOR _552_ (
    .A(_254_),
    .B(_257_),
    .Y(_000_[30])
  );
  NAND _553_ (
    .A(valid_in1),
    .B(lane_in1[31]),
    .Y(_258_)
  );
  NOR _554_ (
    .A(valid_in1),
    .B(_035_),
    .Y(_259_)
  );
  NAND _555_ (
    .A(selector),
    .B(_258_),
    .Y(_260_)
  );
  NOR _556_ (
    .A(_259_),
    .B(_260_),
    .Y(_261_)
  );
  NOR _557_ (
    .A(selector),
    .B(lane_in0[31]),
    .Y(_262_)
  );
  NOR _558_ (
    .A(_038_),
    .B(_262_),
    .Y(_263_)
  );
  NOT _559_ (
    .A(_263_),
    .Y(_264_)
  );
  NOR _560_ (
    .A(_261_),
    .B(_264_),
    .Y(_000_[31])
  );
  (* src = "Unstriping.v:49" *)
  DFF _561_ (
    .C(clk),
    .D(_000_[0]),
    .Q(data_out[0])
  );
  (* src = "Unstriping.v:49" *)
  DFF _562_ (
    .C(clk),
    .D(_000_[1]),
    .Q(data_out[1])
  );
  (* src = "Unstriping.v:49" *)
  DFF _563_ (
    .C(clk),
    .D(_000_[2]),
    .Q(data_out[2])
  );
  (* src = "Unstriping.v:49" *)
  DFF _564_ (
    .C(clk),
    .D(_000_[3]),
    .Q(data_out[3])
  );
  (* src = "Unstriping.v:49" *)
  DFF _565_ (
    .C(clk),
    .D(_000_[4]),
    .Q(data_out[4])
  );
  (* src = "Unstriping.v:49" *)
  DFF _566_ (
    .C(clk),
    .D(_000_[5]),
    .Q(data_out[5])
  );
  (* src = "Unstriping.v:49" *)
  DFF _567_ (
    .C(clk),
    .D(_000_[6]),
    .Q(data_out[6])
  );
  (* src = "Unstriping.v:49" *)
  DFF _568_ (
    .C(clk),
    .D(_000_[7]),
    .Q(data_out[7])
  );
  (* src = "Unstriping.v:49" *)
  DFF _569_ (
    .C(clk),
    .D(_000_[8]),
    .Q(data_out[8])
  );
  (* src = "Unstriping.v:49" *)
  DFF _570_ (
    .C(clk),
    .D(_000_[9]),
    .Q(data_out[9])
  );
  (* src = "Unstriping.v:49" *)
  DFF _571_ (
    .C(clk),
    .D(_000_[10]),
    .Q(data_out[10])
  );
  (* src = "Unstriping.v:49" *)
  DFF _572_ (
    .C(clk),
    .D(_000_[11]),
    .Q(data_out[11])
  );
  (* src = "Unstriping.v:49" *)
  DFF _573_ (
    .C(clk),
    .D(_000_[12]),
    .Q(data_out[12])
  );
  (* src = "Unstriping.v:49" *)
  DFF _574_ (
    .C(clk),
    .D(_000_[13]),
    .Q(data_out[13])
  );
  (* src = "Unstriping.v:49" *)
  DFF _575_ (
    .C(clk),
    .D(_000_[14]),
    .Q(data_out[14])
  );
  (* src = "Unstriping.v:49" *)
  DFF _576_ (
    .C(clk),
    .D(_000_[15]),
    .Q(data_out[15])
  );
  (* src = "Unstriping.v:49" *)
  DFF _577_ (
    .C(clk),
    .D(_000_[16]),
    .Q(data_out[16])
  );
  (* src = "Unstriping.v:49" *)
  DFF _578_ (
    .C(clk),
    .D(_000_[17]),
    .Q(data_out[17])
  );
  (* src = "Unstriping.v:49" *)
  DFF _579_ (
    .C(clk),
    .D(_000_[18]),
    .Q(data_out[18])
  );
  (* src = "Unstriping.v:49" *)
  DFF _580_ (
    .C(clk),
    .D(_000_[19]),
    .Q(data_out[19])
  );
  (* src = "Unstriping.v:49" *)
  DFF _581_ (
    .C(clk),
    .D(_000_[20]),
    .Q(data_out[20])
  );
  (* src = "Unstriping.v:49" *)
  DFF _582_ (
    .C(clk),
    .D(_000_[21]),
    .Q(data_out[21])
  );
  (* src = "Unstriping.v:49" *)
  DFF _583_ (
    .C(clk),
    .D(_000_[22]),
    .Q(data_out[22])
  );
  (* src = "Unstriping.v:49" *)
  DFF _584_ (
    .C(clk),
    .D(_000_[23]),
    .Q(data_out[23])
  );
  (* src = "Unstriping.v:49" *)
  DFF _585_ (
    .C(clk),
    .D(_000_[24]),
    .Q(data_out[24])
  );
  (* src = "Unstriping.v:49" *)
  DFF _586_ (
    .C(clk),
    .D(_000_[25]),
    .Q(data_out[25])
  );
  (* src = "Unstriping.v:49" *)
  DFF _587_ (
    .C(clk),
    .D(_000_[26]),
    .Q(data_out[26])
  );
  (* src = "Unstriping.v:49" *)
  DFF _588_ (
    .C(clk),
    .D(_000_[27]),
    .Q(data_out[27])
  );
  (* src = "Unstriping.v:49" *)
  DFF _589_ (
    .C(clk),
    .D(_000_[28]),
    .Q(data_out[28])
  );
  (* src = "Unstriping.v:49" *)
  DFF _590_ (
    .C(clk),
    .D(_000_[29]),
    .Q(data_out[29])
  );
  (* src = "Unstriping.v:49" *)
  DFF _591_ (
    .C(clk),
    .D(_000_[30]),
    .Q(data_out[30])
  );
  (* src = "Unstriping.v:49" *)
  DFF _592_ (
    .C(clk),
    .D(_000_[31]),
    .Q(data_out[31])
  );
  (* src = "Unstriping.v:49" *)
  DFF _593_ (
    .C(clk),
    .D(_002_),
    .Q(valid_out)
  );
  (* src = "Unstriping.v:49" *)
  DFF _594_ (
    .C(clk),
    .D(_001_),
    .Q(selector)
  );
  assign lane0 = lane_in0;
  assign valid0 = 1'h1;
  assign valid1 = valid_in1;
endmodule
