/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "Maquina_Estado_Estruc.v:4" *)
module Maquina_Estado_Estruc(bus_in, reset, clk, bus_out_Estruc, control_Estruc, error_Estruc);
  (* src = "Maquina_Estado_Estruc.v:43" *)
  wire [3:0] _000_;
  (* src = "Maquina_Estado_Estruc.v:43" *)
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  (* src = "Maquina_Estado_Estruc.v:19" *)
  wire [3:0] Word;
  (* src = "Maquina_Estado_Estruc.v:5" *)
  input [15:0] bus_in;
  (* src = "Maquina_Estado_Estruc.v:8" *)
  output [15:0] bus_out_Estruc;
  (* src = "Maquina_Estado_Estruc.v:7" *)
  input clk;
  (* src = "Maquina_Estado_Estruc.v:9" *)
  output [3:0] control_Estruc;
  (* src = "Maquina_Estado_Estruc.v:10" *)
  output error_Estruc;
  (* onehot = 32'd1 *)
  wire [4:0] estado_Estruc;
  (* src = "Maquina_Estado_Estruc.v:6" *)
  input reset;
  NOT _102_ (
    .A(bus_in[1]),
    .Y(_035_)
  );
  NOT _103_ (
    .A(estado_Estruc[3]),
    .Y(_036_)
  );
  NOT _104_ (
    .A(estado_Estruc[0]),
    .Y(_037_)
  );
  NOT _105_ (
    .A(bus_in[0]),
    .Y(_038_)
  );
  NOT _106_ (
    .A(bus_in[2]),
    .Y(_039_)
  );
  NOT _107_ (
    .A(bus_in[3]),
    .Y(_040_)
  );
  NOT _108_ (
    .A(Word[0]),
    .Y(_041_)
  );
  NOT _109_ (
    .A(Word[1]),
    .Y(_042_)
  );
  NOT _110_ (
    .A(Word[2]),
    .Y(_043_)
  );
  NOT _111_ (
    .A(Word[3]),
    .Y(_044_)
  );
  NOT _112_ (
    .A(reset),
    .Y(_045_)
  );
  NAND _113_ (
    .A(bus_in[12]),
    .B(bus_in[13]),
    .Y(_046_)
  );
  NOT _114_ (
    .A(_046_),
    .Y(_047_)
  );
  NAND _115_ (
    .A(bus_in[14]),
    .B(bus_in[15]),
    .Y(_048_)
  );
  NOT _116_ (
    .A(_048_),
    .Y(_049_)
  );
  NOR _117_ (
    .A(_046_),
    .B(_048_),
    .Y(_050_)
  );
  NAND _118_ (
    .A(_047_),
    .B(_049_),
    .Y(_051_)
  );
  NOR _119_ (
    .A(bus_in[1]),
    .B(bus_in[0]),
    .Y(_052_)
  );
  NAND _120_ (
    .A(_035_),
    .B(_038_),
    .Y(_053_)
  );
  NOR _121_ (
    .A(bus_in[2]),
    .B(bus_in[3]),
    .Y(_054_)
  );
  NOT _122_ (
    .A(_054_),
    .Y(_055_)
  );
  NOR _123_ (
    .A(_053_),
    .B(_055_),
    .Y(_056_)
  );
  NAND _124_ (
    .A(_052_),
    .B(_054_),
    .Y(_057_)
  );
  NOR _125_ (
    .A(_051_),
    .B(_057_),
    .Y(_058_)
  );
  NAND _126_ (
    .A(_050_),
    .B(_056_),
    .Y(_059_)
  );
  NAND _127_ (
    .A(estado_Estruc[0]),
    .B(_059_),
    .Y(_060_)
  );
  NOT _128_ (
    .A(_060_),
    .Y(_061_)
  );
  NAND _129_ (
    .A(reset),
    .B(_060_),
    .Y(_003_)
  );
  NOR _130_ (
    .A(estado_Estruc[2]),
    .B(estado_Estruc[1]),
    .Y(_062_)
  );
  NOT _131_ (
    .A(_062_),
    .Y(_063_)
  );
  NAND _132_ (
    .A(_037_),
    .B(_062_),
    .Y(_064_)
  );
  NAND _133_ (
    .A(reset),
    .B(_064_),
    .Y(_065_)
  );
  NAND _134_ (
    .A(reset),
    .B(_050_),
    .Y(_066_)
  );
  NOR _135_ (
    .A(_059_),
    .B(_065_),
    .Y(_006_)
  );
  NOR _136_ (
    .A(bus_in[1]),
    .B(_038_),
    .Y(_067_)
  );
  NAND _137_ (
    .A(bus_in[0]),
    .B(_054_),
    .Y(_068_)
  );
  NOR _138_ (
    .A(bus_in[1]),
    .B(_068_),
    .Y(_069_)
  );
  NAND _139_ (
    .A(_054_),
    .B(_067_),
    .Y(_070_)
  );
  NOR _140_ (
    .A(_051_),
    .B(_070_),
    .Y(_071_)
  );
  NAND _141_ (
    .A(_050_),
    .B(_069_),
    .Y(_072_)
  );
  NAND _142_ (
    .A(estado_Estruc[4]),
    .B(_071_),
    .Y(_073_)
  );
  NAND _143_ (
    .A(bus_in[1]),
    .B(_042_),
    .Y(_074_)
  );
  NAND _144_ (
    .A(_035_),
    .B(Word[1]),
    .Y(_075_)
  );
  NAND _145_ (
    .A(_074_),
    .B(_075_),
    .Y(_076_)
  );
  NAND _146_ (
    .A(bus_in[0]),
    .B(_041_),
    .Y(_077_)
  );
  NAND _147_ (
    .A(_038_),
    .B(Word[0]),
    .Y(_078_)
  );
  NAND _148_ (
    .A(_077_),
    .B(_078_),
    .Y(_079_)
  );
  NOR _149_ (
    .A(_076_),
    .B(_079_),
    .Y(_080_)
  );
  NAND _150_ (
    .A(bus_in[3]),
    .B(_044_),
    .Y(_081_)
  );
  NAND _151_ (
    .A(_040_),
    .B(Word[3]),
    .Y(_082_)
  );
  NAND _152_ (
    .A(_081_),
    .B(_082_),
    .Y(_083_)
  );
  NAND _153_ (
    .A(bus_in[2]),
    .B(_043_),
    .Y(_084_)
  );
  NAND _154_ (
    .A(_039_),
    .B(Word[2]),
    .Y(_085_)
  );
  NAND _155_ (
    .A(_084_),
    .B(_085_),
    .Y(_086_)
  );
  NOR _156_ (
    .A(_083_),
    .B(_086_),
    .Y(_087_)
  );
  NAND _157_ (
    .A(_080_),
    .B(_087_),
    .Y(_088_)
  );
  NOR _158_ (
    .A(_051_),
    .B(_088_),
    .Y(_089_)
  );
  NAND _159_ (
    .A(estado_Estruc[3]),
    .B(_089_),
    .Y(_090_)
  );
  NAND _160_ (
    .A(_073_),
    .B(_090_),
    .Y(_091_)
  );
  NAND _161_ (
    .A(reset),
    .B(_091_),
    .Y(_092_)
  );
  NOT _162_ (
    .A(_092_),
    .Y(_005_)
  );
  NAND _163_ (
    .A(estado_Estruc[3]),
    .B(_088_),
    .Y(_093_)
  );
  NOR _164_ (
    .A(_056_),
    .B(_062_),
    .Y(_094_)
  );
  NAND _165_ (
    .A(estado_Estruc[4]),
    .B(_070_),
    .Y(_095_)
  );
  NAND _166_ (
    .A(_093_),
    .B(_095_),
    .Y(_096_)
  );
  NOR _167_ (
    .A(_094_),
    .B(_096_),
    .Y(_097_)
  );
  NOR _168_ (
    .A(_066_),
    .B(_097_),
    .Y(_004_)
  );
  NOR _169_ (
    .A(Word[0]),
    .B(_058_),
    .Y(_098_)
  );
  NOR _170_ (
    .A(_037_),
    .B(_098_),
    .Y(_099_)
  );
  NOR _171_ (
    .A(bus_in[0]),
    .B(_090_),
    .Y(_100_)
  );
  NOR _172_ (
    .A(_099_),
    .B(_100_),
    .Y(_101_)
  );
  NOR _173_ (
    .A(_045_),
    .B(_101_),
    .Y(_000_[0])
  );
  NAND _174_ (
    .A(bus_in[1]),
    .B(bus_in[0]),
    .Y(_007_)
  );
  NOT _175_ (
    .A(_007_),
    .Y(_008_)
  );
  NAND _176_ (
    .A(_053_),
    .B(_007_),
    .Y(_009_)
  );
  NOR _177_ (
    .A(_090_),
    .B(_009_),
    .Y(_010_)
  );
  NAND _178_ (
    .A(Word[1]),
    .B(_061_),
    .Y(_011_)
  );
  NAND _179_ (
    .A(_073_),
    .B(_011_),
    .Y(_012_)
  );
  NOR _180_ (
    .A(_010_),
    .B(_012_),
    .Y(_013_)
  );
  NOR _181_ (
    .A(_045_),
    .B(_013_),
    .Y(_000_[1])
  );
  NOR _182_ (
    .A(_043_),
    .B(_060_),
    .Y(_014_)
  );
  NAND _183_ (
    .A(_039_),
    .B(_007_),
    .Y(_015_)
  );
  NAND _184_ (
    .A(bus_in[2]),
    .B(_008_),
    .Y(_016_)
  );
  NAND _185_ (
    .A(_015_),
    .B(_016_),
    .Y(_017_)
  );
  NOR _186_ (
    .A(_090_),
    .B(_017_),
    .Y(_018_)
  );
  NOR _187_ (
    .A(_014_),
    .B(_018_),
    .Y(_019_)
  );
  NOR _188_ (
    .A(_045_),
    .B(_019_),
    .Y(_000_[2])
  );
  NOR _189_ (
    .A(_044_),
    .B(_060_),
    .Y(_020_)
  );
  NAND _190_ (
    .A(bus_in[3]),
    .B(_016_),
    .Y(_021_)
  );
  NOT _191_ (
    .A(_021_),
    .Y(_022_)
  );
  NOR _192_ (
    .A(bus_in[3]),
    .B(_016_),
    .Y(_023_)
  );
  NOR _193_ (
    .A(_022_),
    .B(_023_),
    .Y(_024_)
  );
  NOR _194_ (
    .A(_090_),
    .B(_024_),
    .Y(_025_)
  );
  NOR _195_ (
    .A(_020_),
    .B(_025_),
    .Y(_026_)
  );
  NOR _196_ (
    .A(_045_),
    .B(_026_),
    .Y(_000_[3])
  );
  NOR _197_ (
    .A(_036_),
    .B(_089_),
    .Y(_027_)
  );
  NAND _198_ (
    .A(_059_),
    .B(_063_),
    .Y(_028_)
  );
  NAND _199_ (
    .A(estado_Estruc[4]),
    .B(_072_),
    .Y(_029_)
  );
  NAND _200_ (
    .A(_028_),
    .B(_029_),
    .Y(_030_)
  );
  NOR _201_ (
    .A(_027_),
    .B(_030_),
    .Y(_031_)
  );
  NOR _202_ (
    .A(_045_),
    .B(_031_),
    .Y(_001_)
  );
  NAND _203_ (
    .A(_036_),
    .B(_062_),
    .Y(_032_)
  );
  NOR _204_ (
    .A(estado_Estruc[4]),
    .B(_032_),
    .Y(_033_)
  );
  NAND _205_ (
    .A(reset),
    .B(_051_),
    .Y(_034_)
  );
  NOR _206_ (
    .A(_033_),
    .B(_034_),
    .Y(_002_)
  );
  DFF _207_ (
    .C(clk),
    .D(_003_),
    .Q(estado_Estruc[0])
  );
  DFF _208_ (
    .C(clk),
    .D(_004_),
    .Q(estado_Estruc[1])
  );
  DFF _209_ (
    .C(clk),
    .D(_002_),
    .Q(estado_Estruc[2])
  );
  DFF _210_ (
    .C(clk),
    .D(_005_),
    .Q(estado_Estruc[3])
  );
  DFF _211_ (
    .C(clk),
    .D(_006_),
    .Q(estado_Estruc[4])
  );
  (* src = "Maquina_Estado_Estruc.v:43" *)
  DFF _212_ (
    .C(clk),
    .D(_001_),
    .Q(error_Estruc)
  );
  (* src = "Maquina_Estado_Estruc.v:43" *)
  DFF _213_ (
    .C(clk),
    .D(_000_[0]),
    .Q(Word[0])
  );
  (* src = "Maquina_Estado_Estruc.v:43" *)
  DFF _214_ (
    .C(clk),
    .D(_000_[1]),
    .Q(Word[1])
  );
  (* src = "Maquina_Estado_Estruc.v:43" *)
  DFF _215_ (
    .C(clk),
    .D(_000_[2]),
    .Q(Word[2])
  );
  (* src = "Maquina_Estado_Estruc.v:43" *)
  DFF _216_ (
    .C(clk),
    .D(_000_[3]),
    .Q(Word[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "Maquina_Estado_Estruc.v:36" *)
  control_Estrucador _217_ (
    .cont_in({ 1'h0, bus_in[3:0] }),
    .cont_out(control_Estruc[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "Maquina_Estado_Estruc.v:37" *)
  reverter_Estruc _218_ (
    .revert_in(bus_in[3:0]),
    .revert_out(bus_out_Estruc[15:12])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "Maquina_Estado_Estruc.v:36" *)
  control_Estrucador _219_ (
    .cont_in({ 1'h0, bus_in[7:4] }),
    .cont_out(control_Estruc[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "Maquina_Estado_Estruc.v:37" *)
  reverter_Estruc _220_ (
    .revert_in(bus_in[7:4]),
    .revert_out(bus_out_Estruc[11:8])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "Maquina_Estado_Estruc.v:36" *)
  control_Estrucador _221_ (
    .cont_in({ 1'h0, bus_in[11:8] }),
    .cont_out(control_Estruc[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "Maquina_Estado_Estruc.v:37" *)
  reverter_Estruc _222_ (
    .revert_in(bus_in[11:8]),
    .revert_out(bus_out_Estruc[7:4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "Maquina_Estado_Estruc.v:36" *)
  control_Estrucador _223_ (
    .cont_in({ 1'h0, bus_in[15:12] }),
    .cont_out(control_Estruc[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "Maquina_Estado_Estruc.v:37" *)
  reverter_Estruc _224_ (
    .revert_in(bus_in[15:12]),
    .revert_out(bus_out_Estruc[3:0])
  );
endmodule

(* dynports =  1  *)
(* src = "control_Estrucador.v:1" *)
module control_Estrucador(cont_in, cont_out);
  wire _0_;
  wire _1_;
  wire _2_;
  wire _3_;
  (* src = "control_Estrucador.v:2" *)
  input [4:0] cont_in;
  (* src = "control_Estrucador.v:3" *)
  output cont_out;
  NOR _4_ (
    .A(cont_in[4]),
    .B(cont_in[3]),
    .Y(_1_)
  );
  NOR _5_ (
    .A(cont_in[2]),
    .B(cont_in[1]),
    .Y(_2_)
  );
  NOT _6_ (
    .A(_2_),
    .Y(_3_)
  );
  NOR _7_ (
    .A(cont_in[0]),
    .B(_3_),
    .Y(_0_)
  );
  NAND _8_ (
    .A(_1_),
    .B(_0_),
    .Y(cont_out)
  );
endmodule

(* dynports =  1  *)
(* src = "reverter_Estruc.v:1" *)
module reverter_Estruc(revert_in, revert_out);
  (* src = "reverter_Estruc.v:3" *)
  input [3:0] revert_in;
  (* src = "reverter_Estruc.v:4" *)
  output [3:0] revert_out;
  assign revert_out = revert_in;
endmodule
