/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "Mux_Conductual_2x1_2bits_Estruc.v:1" *)
module Mux_Conductual_2x1_2bits_Estruc(data_out_Estruc, valid_out1_Estruc, clok, valid1, valid2, reset_L, selector, data_in0, data_in1);
  (* src = "Mux_Conductual_2x1_2bits_Estruc.v:12" *)
  wire [1:0] _00_;
  (* src = "Mux_Conductual_2x1_2bits_Estruc.v:12" *)
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  (* src = "Mux_Conductual_2x1_2bits_Estruc.v:4" *)
  input clok;
  (* src = "Mux_Conductual_2x1_2bits_Estruc.v:9" *)
  input [1:0] data_in0;
  (* src = "Mux_Conductual_2x1_2bits_Estruc.v:10" *)
  input [1:0] data_in1;
  (* src = "Mux_Conductual_2x1_2bits_Estruc.v:2" *)
  output [1:0] data_out_Estruc;
  (* src = "Mux_Conductual_2x1_2bits_Estruc.v:7" *)
  input reset_L;
  (* src = "Mux_Conductual_2x1_2bits_Estruc.v:8" *)
  input selector;
  (* src = "Mux_Conductual_2x1_2bits_Estruc.v:5" *)
  input valid1;
  (* src = "Mux_Conductual_2x1_2bits_Estruc.v:6" *)
  input valid2;
  (* src = "Mux_Conductual_2x1_2bits_Estruc.v:3" *)
  output valid_out1_Estruc;
  NAND _22_ (
    .A(data_in1[1]),
    .B(_06_),
    .Y(_17_)
  );
  NAND _23_ (
    .A(_02_),
    .B(_09_),
    .Y(_18_)
  );
  NOR _24_ (
    .A(data_out_Estruc[1]),
    .B(_09_),
    .Y(_19_)
  );
  NOR _25_ (
    .A(_12_),
    .B(_19_),
    .Y(_20_)
  );
  NAND _26_ (
    .A(_18_),
    .B(_20_),
    .Y(_21_)
  );
  NAND _27_ (
    .A(_17_),
    .B(_21_),
    .Y(_00_[1])
  );
  NAND _28_ (
    .A(_07_),
    .B(_10_),
    .Y(_01_)
  );
  NOT _29_ (
    .A(data_in0[1]),
    .Y(_02_)
  );
  NOT _30_ (
    .A(selector),
    .Y(_03_)
  );
  NOT _31_ (
    .A(valid1),
    .Y(_04_)
  );
  NOT _32_ (
    .A(valid2),
    .Y(_05_)
  );
  NOR _33_ (
    .A(_03_),
    .B(_05_),
    .Y(_06_)
  );
  NAND _34_ (
    .A(selector),
    .B(valid2),
    .Y(_07_)
  );
  NAND _35_ (
    .A(data_in1[0]),
    .B(_06_),
    .Y(_08_)
  );
  NOR _36_ (
    .A(selector),
    .B(_04_),
    .Y(_09_)
  );
  NAND _37_ (
    .A(_03_),
    .B(valid1),
    .Y(_10_)
  );
  NOR _38_ (
    .A(data_out_Estruc[0]),
    .B(_09_),
    .Y(_11_)
  );
  NAND _39_ (
    .A(reset_L),
    .B(_07_),
    .Y(_12_)
  );
  NOT _40_ (
    .A(_12_),
    .Y(_13_)
  );
  NOR _41_ (
    .A(data_in0[0]),
    .B(_10_),
    .Y(_14_)
  );
  NOR _42_ (
    .A(_11_),
    .B(_14_),
    .Y(_15_)
  );
  NAND _43_ (
    .A(_13_),
    .B(_15_),
    .Y(_16_)
  );
  NAND _44_ (
    .A(_08_),
    .B(_16_),
    .Y(_00_[0])
  );
  (* src = "Mux_Conductual_2x1_2bits_Estruc.v:12" *)
  DFF _45_ (
    .C(clok),
    .D(_00_[0]),
    .Q(data_out_Estruc[0])
  );
  (* src = "Mux_Conductual_2x1_2bits_Estruc.v:12" *)
  DFF _46_ (
    .C(clok),
    .D(_00_[1]),
    .Q(data_out_Estruc[1])
  );
  (* src = "Mux_Conductual_2x1_2bits_Estruc.v:12" *)
  DFF _47_ (
    .C(clok),
    .D(_01_),
    .Q(valid_out1_Estruc)
  );
endmodule
