/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "Serial_Paralelo_Estruc.v:1" *)
module Serial_Paralelo_Estruc(data_out_SP_Estruc, valid_SP_Estruc, active_Estruc, clk_32f, data_in_SP, reset_L);
  (* src = "Serial_Paralelo_Estruc.v:40" *)
  wire _000_;
  (* src = "Serial_Paralelo_Estruc.v:40" *)
  wire [1:0] _001_;
  (* src = "Serial_Paralelo_Estruc.v:40" *)
  wire [7:0] _002_;
  (* src = "Serial_Paralelo_Estruc.v:40" *)
  wire _003_;
  (* src = "Serial_Paralelo_Estruc.v:40" *)
  wire [2:0] _004_;
  (* src = "Serial_Paralelo_Estruc.v:40" *)
  wire [2:0] _005_;
  (* src = "Serial_Paralelo_Estruc.v:40" *)
  wire [7:0] _006_;
  (* src = "Serial_Paralelo_Estruc.v:40" *)
  wire [7:0] _007_;
  (* src = "Serial_Paralelo_Estruc.v:40" *)
  wire [2:0] _008_;
  (* src = "Serial_Paralelo_Estruc.v:40" *)
  wire [2:0] _009_;
  (* src = "Serial_Paralelo_Estruc.v:40" *)
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire _283_;
  wire _284_;
  wire _285_;
  wire _286_;
  wire _287_;
  wire _288_;
  wire _289_;
  wire _290_;
  wire _291_;
  wire _292_;
  wire _293_;
  wire _294_;
  wire _295_;
  wire _296_;
  wire _297_;
  wire _298_;
  wire _299_;
  wire _300_;
  wire _301_;
  wire _302_;
  (* src = "Serial_Paralelo_Estruc.v:18" *)
  wire Aux1;
  (* src = "Serial_Paralelo_Estruc.v:4" *)
  output active_Estruc;
  (* src = "Serial_Paralelo_Estruc.v:5" *)
  input clk_32f;
  (* src = "Serial_Paralelo_Estruc.v:11" *)
  wire [1:0] cont;
  (* src = "Serial_Paralelo_Estruc.v:6" *)
  input data_in_SP;
  (* src = "Serial_Paralelo_Estruc.v:2" *)
  output [7:0] data_out_SP_Estruc;
  (* src = "Serial_Paralelo_Estruc.v:16" *)
  wire flag2;
  (* src = "Serial_Paralelo_Estruc.v:19" *)
  wire [2:0] flag3;
  (* src = "Serial_Paralelo_Estruc.v:12" *)
  wire [2:0] i;
  (* src = "Serial_Paralelo_Estruc.v:9" *)
  wire [7:0] inic;
  (* src = "Serial_Paralelo_Estruc.v:10" *)
  wire [7:0] inic2;
  (* src = "Serial_Paralelo_Estruc.v:13" *)
  wire [2:0] j;
  (* src = "Serial_Paralelo_Estruc.v:14" *)
  wire [2:0] k;
  (* src = "Serial_Paralelo_Estruc.v:7" *)
  input reset_L;
  (* src = "Serial_Paralelo_Estruc.v:3" *)
  output valid_SP_Estruc;
  NOT _303_ (
    .A(flag3[0]),
    .Y(_289_)
  );
  NOT _304_ (
    .A(flag3[1]),
    .Y(_290_)
  );
  NOT _305_ (
    .A(inic2[6]),
    .Y(_291_)
  );
  NOT _306_ (
    .A(inic[0]),
    .Y(_292_)
  );
  NOT _307_ (
    .A(i[2]),
    .Y(_293_)
  );
  NOT _308_ (
    .A(i[0]),
    .Y(_294_)
  );
  NOT _309_ (
    .A(i[1]),
    .Y(_295_)
  );
  NOT _310_ (
    .A(j[2]),
    .Y(_296_)
  );
  NOT _311_ (
    .A(j[0]),
    .Y(_297_)
  );
  NOT _312_ (
    .A(j[1]),
    .Y(_298_)
  );
  NOT _313_ (
    .A(reset_L),
    .Y(_299_)
  );
  NOT _314_ (
    .A(data_in_SP),
    .Y(_300_)
  );
  NOT _315_ (
    .A(data_out_SP_Estruc[0]),
    .Y(_301_)
  );
  NOT _316_ (
    .A(inic[5]),
    .Y(_302_)
  );
  NOT _317_ (
    .A(inic2[5]),
    .Y(_011_)
  );
  NOT _318_ (
    .A(Aux1),
    .Y(_012_)
  );
  NOT _319_ (
    .A(k[0]),
    .Y(_013_)
  );
  NOT _320_ (
    .A(k[2]),
    .Y(_014_)
  );
  NOT _321_ (
    .A(valid_SP_Estruc),
    .Y(_015_)
  );
  NOT _322_ (
    .A(inic[7]),
    .Y(_016_)
  );
  NOT _323_ (
    .A(cont[0]),
    .Y(_017_)
  );
  NOT _324_ (
    .A(cont[1]),
    .Y(_018_)
  );
  NOT _325_ (
    .A(flag3[2]),
    .Y(_019_)
  );
  NAND _326_ (
    .A(inic2[4]),
    .B(inic2[3]),
    .Y(_020_)
  );
  NAND _327_ (
    .A(inic2[2]),
    .B(inic2[7]),
    .Y(_021_)
  );
  NOR _328_ (
    .A(_020_),
    .B(_021_),
    .Y(_022_)
  );
  NOT _329_ (
    .A(_022_),
    .Y(_023_)
  );
  NOR _330_ (
    .A(inic2[0]),
    .B(inic2[1]),
    .Y(_024_)
  );
  NOT _331_ (
    .A(_024_),
    .Y(_025_)
  );
  NOR _332_ (
    .A(inic2[6]),
    .B(_011_),
    .Y(_026_)
  );
  NAND _333_ (
    .A(_291_),
    .B(inic2[5]),
    .Y(_027_)
  );
  NOR _334_ (
    .A(_025_),
    .B(_027_),
    .Y(_028_)
  );
  NAND _335_ (
    .A(_024_),
    .B(_026_),
    .Y(_029_)
  );
  NOR _336_ (
    .A(_023_),
    .B(_029_),
    .Y(_030_)
  );
  NAND _337_ (
    .A(_022_),
    .B(_028_),
    .Y(_031_)
  );
  NAND _338_ (
    .A(j[2]),
    .B(cont[0]),
    .Y(_032_)
  );
  NAND _339_ (
    .A(cont[1]),
    .B(flag3[2]),
    .Y(_033_)
  );
  NOR _340_ (
    .A(_032_),
    .B(_033_),
    .Y(_034_)
  );
  NAND _341_ (
    .A(j[0]),
    .B(j[1]),
    .Y(_035_)
  );
  NOR _342_ (
    .A(flag3[0]),
    .B(flag3[1]),
    .Y(_036_)
  );
  NAND _343_ (
    .A(_289_),
    .B(_290_),
    .Y(_037_)
  );
  NOR _344_ (
    .A(_035_),
    .B(_037_),
    .Y(_038_)
  );
  NAND _345_ (
    .A(_034_),
    .B(_038_),
    .Y(_039_)
  );
  NOR _346_ (
    .A(_031_),
    .B(_039_),
    .Y(_040_)
  );
  NAND _347_ (
    .A(reset_L),
    .B(_040_),
    .Y(_041_)
  );
  NOT _348_ (
    .A(_041_),
    .Y(active_Estruc)
  );
  NAND _349_ (
    .A(data_out_SP_Estruc[7]),
    .B(reset_L),
    .Y(_042_)
  );
  NAND _350_ (
    .A(i[0]),
    .B(i[1]),
    .Y(_043_)
  );
  NOT _351_ (
    .A(_043_),
    .Y(_044_)
  );
  NOR _352_ (
    .A(_017_),
    .B(_018_),
    .Y(_045_)
  );
  NAND _353_ (
    .A(cont[0]),
    .B(cont[1]),
    .Y(_046_)
  );
  NOR _354_ (
    .A(_037_),
    .B(_046_),
    .Y(_047_)
  );
  NAND _355_ (
    .A(_036_),
    .B(_045_),
    .Y(_048_)
  );
  NAND _356_ (
    .A(j[2]),
    .B(flag3[2]),
    .Y(_049_)
  );
  NOR _357_ (
    .A(_035_),
    .B(_049_),
    .Y(_050_)
  );
  NOT _358_ (
    .A(_050_),
    .Y(_051_)
  );
  NOR _359_ (
    .A(_048_),
    .B(_051_),
    .Y(_052_)
  );
  NAND _360_ (
    .A(_047_),
    .B(_050_),
    .Y(_053_)
  );
  NOR _361_ (
    .A(_031_),
    .B(_053_),
    .Y(_054_)
  );
  NAND _362_ (
    .A(_030_),
    .B(_052_),
    .Y(_055_)
  );
  NOR _363_ (
    .A(_299_),
    .B(_055_),
    .Y(_056_)
  );
  NAND _364_ (
    .A(reset_L),
    .B(_054_),
    .Y(_057_)
  );
  NOR _365_ (
    .A(_293_),
    .B(_057_),
    .Y(_058_)
  );
  NAND _366_ (
    .A(i[2]),
    .B(_056_),
    .Y(_059_)
  );
  NOR _367_ (
    .A(_043_),
    .B(_059_),
    .Y(_060_)
  );
  NAND _368_ (
    .A(_044_),
    .B(_058_),
    .Y(_061_)
  );
  NOR _369_ (
    .A(_042_),
    .B(_060_),
    .Y(_062_)
  );
  NOR _370_ (
    .A(_300_),
    .B(_061_),
    .Y(_063_)
  );
  NAND _371_ (
    .A(data_in_SP),
    .B(_060_),
    .Y(_064_)
  );
  NOR _372_ (
    .A(_062_),
    .B(_063_),
    .Y(_065_)
  );
  NAND _373_ (
    .A(k[1]),
    .B(k[2]),
    .Y(_066_)
  );
  NOT _374_ (
    .A(_066_),
    .Y(_067_)
  );
  NOR _375_ (
    .A(_016_),
    .B(_066_),
    .Y(_068_)
  );
  NAND _376_ (
    .A(inic[7]),
    .B(_067_),
    .Y(_069_)
  );
  NAND _377_ (
    .A(inic[4]),
    .B(inic[3]),
    .Y(_070_)
  );
  NOT _378_ (
    .A(_070_),
    .Y(_071_)
  );
  NAND _379_ (
    .A(inic[2]),
    .B(k[0]),
    .Y(_072_)
  );
  NOT _380_ (
    .A(_072_),
    .Y(_073_)
  );
  NAND _381_ (
    .A(_071_),
    .B(_073_),
    .Y(_074_)
  );
  NOR _382_ (
    .A(inic[0]),
    .B(inic[1]),
    .Y(_075_)
  );
  NOR _383_ (
    .A(inic[6]),
    .B(_302_),
    .Y(_076_)
  );
  NAND _384_ (
    .A(_075_),
    .B(_076_),
    .Y(_077_)
  );
  NOR _385_ (
    .A(_074_),
    .B(_077_),
    .Y(_078_)
  );
  NAND _386_ (
    .A(_068_),
    .B(_078_),
    .Y(_079_)
  );
  NOR _387_ (
    .A(_041_),
    .B(_079_),
    .Y(_080_)
  );
  NAND _388_ (
    .A(_292_),
    .B(inic[5]),
    .Y(_081_)
  );
  NOR _389_ (
    .A(_074_),
    .B(_081_),
    .Y(_082_)
  );
  NOR _390_ (
    .A(inic[1]),
    .B(inic[6]),
    .Y(_083_)
  );
  NOT _391_ (
    .A(_083_),
    .Y(_084_)
  );
  NOR _392_ (
    .A(_069_),
    .B(_084_),
    .Y(_085_)
  );
  NAND _393_ (
    .A(_082_),
    .B(_085_),
    .Y(_086_)
  );
  NOR _394_ (
    .A(_065_),
    .B(_080_),
    .Y(_002_[7])
  );
  NAND _395_ (
    .A(reset_L),
    .B(data_out_SP_Estruc[5]),
    .Y(_087_)
  );
  NOR _396_ (
    .A(_294_),
    .B(i[1]),
    .Y(_088_)
  );
  NAND _397_ (
    .A(i[0]),
    .B(_295_),
    .Y(_089_)
  );
  NOR _398_ (
    .A(_059_),
    .B(_089_),
    .Y(_090_)
  );
  NAND _399_ (
    .A(_058_),
    .B(_088_),
    .Y(_091_)
  );
  NOR _400_ (
    .A(_087_),
    .B(_090_),
    .Y(_092_)
  );
  NOR _401_ (
    .A(_300_),
    .B(_091_),
    .Y(_093_)
  );
  NAND _402_ (
    .A(data_in_SP),
    .B(_090_),
    .Y(_094_)
  );
  NOR _403_ (
    .A(_092_),
    .B(_093_),
    .Y(_095_)
  );
  NOR _404_ (
    .A(_080_),
    .B(_095_),
    .Y(_002_[5])
  );
  NAND _405_ (
    .A(reset_L),
    .B(data_out_SP_Estruc[4]),
    .Y(_096_)
  );
  NOR _406_ (
    .A(i[0]),
    .B(i[1]),
    .Y(_097_)
  );
  NAND _407_ (
    .A(_294_),
    .B(_295_),
    .Y(_098_)
  );
  NOR _408_ (
    .A(_059_),
    .B(_098_),
    .Y(_099_)
  );
  NAND _409_ (
    .A(_058_),
    .B(_097_),
    .Y(_100_)
  );
  NOR _410_ (
    .A(_096_),
    .B(_099_),
    .Y(_101_)
  );
  NOR _411_ (
    .A(_300_),
    .B(_100_),
    .Y(_102_)
  );
  NAND _412_ (
    .A(data_in_SP),
    .B(_099_),
    .Y(_103_)
  );
  NOR _413_ (
    .A(_101_),
    .B(_102_),
    .Y(_104_)
  );
  NOR _414_ (
    .A(_080_),
    .B(_104_),
    .Y(_002_[4])
  );
  NAND _415_ (
    .A(reset_L),
    .B(data_out_SP_Estruc[3]),
    .Y(_105_)
  );
  NOR _416_ (
    .A(i[2]),
    .B(_057_),
    .Y(_106_)
  );
  NAND _417_ (
    .A(_293_),
    .B(_056_),
    .Y(_107_)
  );
  NOR _418_ (
    .A(_043_),
    .B(_107_),
    .Y(_108_)
  );
  NAND _419_ (
    .A(_044_),
    .B(_106_),
    .Y(_109_)
  );
  NOR _420_ (
    .A(_105_),
    .B(_108_),
    .Y(_110_)
  );
  NOR _421_ (
    .A(_300_),
    .B(_109_),
    .Y(_111_)
  );
  NAND _422_ (
    .A(data_in_SP),
    .B(_108_),
    .Y(_112_)
  );
  NOR _423_ (
    .A(_110_),
    .B(_111_),
    .Y(_113_)
  );
  NOR _424_ (
    .A(_080_),
    .B(_113_),
    .Y(_002_[3])
  );
  NAND _425_ (
    .A(reset_L),
    .B(data_out_SP_Estruc[2]),
    .Y(_114_)
  );
  NOR _426_ (
    .A(i[0]),
    .B(_295_),
    .Y(_115_)
  );
  NAND _427_ (
    .A(_294_),
    .B(i[1]),
    .Y(_116_)
  );
  NOR _428_ (
    .A(_107_),
    .B(_116_),
    .Y(_117_)
  );
  NAND _429_ (
    .A(_106_),
    .B(_115_),
    .Y(_118_)
  );
  NOR _430_ (
    .A(_114_),
    .B(_117_),
    .Y(_119_)
  );
  NOR _431_ (
    .A(_300_),
    .B(_118_),
    .Y(_120_)
  );
  NAND _432_ (
    .A(data_in_SP),
    .B(_117_),
    .Y(_121_)
  );
  NOR _433_ (
    .A(_119_),
    .B(_120_),
    .Y(_122_)
  );
  NOR _434_ (
    .A(_080_),
    .B(_122_),
    .Y(_002_[2])
  );
  NAND _435_ (
    .A(reset_L),
    .B(data_out_SP_Estruc[1]),
    .Y(_123_)
  );
  NOR _436_ (
    .A(_089_),
    .B(_107_),
    .Y(_124_)
  );
  NAND _437_ (
    .A(_088_),
    .B(_106_),
    .Y(_125_)
  );
  NOR _438_ (
    .A(_123_),
    .B(_124_),
    .Y(_126_)
  );
  NOR _439_ (
    .A(_300_),
    .B(_125_),
    .Y(_127_)
  );
  NAND _440_ (
    .A(data_in_SP),
    .B(_124_),
    .Y(_128_)
  );
  NOR _441_ (
    .A(_126_),
    .B(_127_),
    .Y(_129_)
  );
  NOR _442_ (
    .A(_080_),
    .B(_129_),
    .Y(_002_[1])
  );
  NOR _443_ (
    .A(_055_),
    .B(_098_),
    .Y(_130_)
  );
  NAND _444_ (
    .A(_054_),
    .B(_097_),
    .Y(_131_)
  );
  NOR _445_ (
    .A(i[2]),
    .B(_131_),
    .Y(_132_)
  );
  NAND _446_ (
    .A(_293_),
    .B(_130_),
    .Y(_133_)
  );
  NOR _447_ (
    .A(_299_),
    .B(_132_),
    .Y(_134_)
  );
  NAND _448_ (
    .A(reset_L),
    .B(_133_),
    .Y(_135_)
  );
  NOR _449_ (
    .A(_301_),
    .B(_135_),
    .Y(_136_)
  );
  NOR _450_ (
    .A(_299_),
    .B(_133_),
    .Y(_137_)
  );
  NAND _451_ (
    .A(reset_L),
    .B(_132_),
    .Y(_138_)
  );
  NOR _452_ (
    .A(_300_),
    .B(_138_),
    .Y(_139_)
  );
  NAND _453_ (
    .A(data_in_SP),
    .B(_137_),
    .Y(_140_)
  );
  NOR _454_ (
    .A(_136_),
    .B(_139_),
    .Y(_141_)
  );
  NOR _455_ (
    .A(_080_),
    .B(_141_),
    .Y(_002_[0])
  );
  NAND _456_ (
    .A(reset_L),
    .B(data_out_SP_Estruc[6]),
    .Y(_142_)
  );
  NOR _457_ (
    .A(_059_),
    .B(_116_),
    .Y(_143_)
  );
  NAND _458_ (
    .A(_058_),
    .B(_115_),
    .Y(_144_)
  );
  NOR _459_ (
    .A(_142_),
    .B(_143_),
    .Y(_145_)
  );
  NOR _460_ (
    .A(_300_),
    .B(_144_),
    .Y(_146_)
  );
  NAND _461_ (
    .A(data_in_SP),
    .B(_143_),
    .Y(_147_)
  );
  NOR _462_ (
    .A(_145_),
    .B(_146_),
    .Y(_148_)
  );
  NOR _463_ (
    .A(_080_),
    .B(_148_),
    .Y(_002_[6])
  );
  NAND _464_ (
    .A(inic[6]),
    .B(reset_L),
    .Y(_149_)
  );
  NOR _465_ (
    .A(_143_),
    .B(_149_),
    .Y(_150_)
  );
  NOT _466_ (
    .A(_150_),
    .Y(_151_)
  );
  NAND _467_ (
    .A(_147_),
    .B(_151_),
    .Y(_007_[6])
  );
  NAND _468_ (
    .A(reset_L),
    .B(inic[5]),
    .Y(_152_)
  );
  NOR _469_ (
    .A(_090_),
    .B(_152_),
    .Y(_153_)
  );
  NOT _470_ (
    .A(_153_),
    .Y(_154_)
  );
  NAND _471_ (
    .A(_094_),
    .B(_154_),
    .Y(_007_[5])
  );
  NAND _472_ (
    .A(reset_L),
    .B(inic[4]),
    .Y(_155_)
  );
  NOT _473_ (
    .A(_155_),
    .Y(_156_)
  );
  NAND _474_ (
    .A(_100_),
    .B(_156_),
    .Y(_157_)
  );
  NAND _475_ (
    .A(_103_),
    .B(_157_),
    .Y(_007_[4])
  );
  NAND _476_ (
    .A(reset_L),
    .B(inic[3]),
    .Y(_158_)
  );
  NOR _477_ (
    .A(_108_),
    .B(_158_),
    .Y(_159_)
  );
  NOT _478_ (
    .A(_159_),
    .Y(_160_)
  );
  NAND _479_ (
    .A(_112_),
    .B(_160_),
    .Y(_007_[3])
  );
  NAND _480_ (
    .A(reset_L),
    .B(inic[2]),
    .Y(_161_)
  );
  NOT _481_ (
    .A(_161_),
    .Y(_162_)
  );
  NAND _482_ (
    .A(_118_),
    .B(_162_),
    .Y(_163_)
  );
  NAND _483_ (
    .A(_121_),
    .B(_163_),
    .Y(_007_[2])
  );
  NAND _484_ (
    .A(inic[1]),
    .B(reset_L),
    .Y(_164_)
  );
  NOT _485_ (
    .A(_164_),
    .Y(_165_)
  );
  NAND _486_ (
    .A(_125_),
    .B(_165_),
    .Y(_166_)
  );
  NAND _487_ (
    .A(_128_),
    .B(_166_),
    .Y(_007_[1])
  );
  NAND _488_ (
    .A(inic[0]),
    .B(_134_),
    .Y(_167_)
  );
  NAND _489_ (
    .A(_140_),
    .B(_167_),
    .Y(_007_[0])
  );
  NOR _490_ (
    .A(j[0]),
    .B(_298_),
    .Y(_168_)
  );
  NAND _491_ (
    .A(_297_),
    .B(j[1]),
    .Y(_169_)
  );
  NAND _492_ (
    .A(reset_L),
    .B(flag2),
    .Y(_170_)
  );
  NAND _493_ (
    .A(_300_),
    .B(_170_),
    .Y(_003_)
  );
  NOR _494_ (
    .A(data_in_SP),
    .B(flag2),
    .Y(_171_)
  );
  NOR _495_ (
    .A(_299_),
    .B(_171_),
    .Y(_172_)
  );
  NAND _496_ (
    .A(reset_L),
    .B(_003_),
    .Y(_173_)
  );
  NOR _497_ (
    .A(_054_),
    .B(_173_),
    .Y(_174_)
  );
  NAND _498_ (
    .A(_055_),
    .B(_172_),
    .Y(_175_)
  );
  NAND _499_ (
    .A(j[2]),
    .B(_174_),
    .Y(_176_)
  );
  NOR _500_ (
    .A(_169_),
    .B(_176_),
    .Y(_177_)
  );
  NAND _501_ (
    .A(inic2[6]),
    .B(reset_L),
    .Y(_178_)
  );
  NAND _502_ (
    .A(data_in_SP),
    .B(_177_),
    .Y(_179_)
  );
  NOR _503_ (
    .A(_177_),
    .B(_178_),
    .Y(_180_)
  );
  NOT _504_ (
    .A(_180_),
    .Y(_181_)
  );
  NAND _505_ (
    .A(_179_),
    .B(_181_),
    .Y(_006_[6])
  );
  NOR _506_ (
    .A(_297_),
    .B(j[1]),
    .Y(_182_)
  );
  NAND _507_ (
    .A(j[0]),
    .B(_298_),
    .Y(_183_)
  );
  NOR _508_ (
    .A(_176_),
    .B(_183_),
    .Y(_184_)
  );
  NAND _509_ (
    .A(reset_L),
    .B(inic2[5]),
    .Y(_185_)
  );
  NAND _510_ (
    .A(data_in_SP),
    .B(_184_),
    .Y(_186_)
  );
  NOR _511_ (
    .A(_184_),
    .B(_185_),
    .Y(_187_)
  );
  NOT _512_ (
    .A(_187_),
    .Y(_188_)
  );
  NAND _513_ (
    .A(_186_),
    .B(_188_),
    .Y(_006_[5])
  );
  NOR _514_ (
    .A(j[0]),
    .B(j[1]),
    .Y(_189_)
  );
  NAND _515_ (
    .A(_297_),
    .B(_298_),
    .Y(_190_)
  );
  NOR _516_ (
    .A(_176_),
    .B(_190_),
    .Y(_191_)
  );
  NAND _517_ (
    .A(reset_L),
    .B(inic2[4]),
    .Y(_192_)
  );
  NAND _518_ (
    .A(data_in_SP),
    .B(_191_),
    .Y(_193_)
  );
  NOR _519_ (
    .A(_191_),
    .B(_192_),
    .Y(_194_)
  );
  NOT _520_ (
    .A(_194_),
    .Y(_195_)
  );
  NAND _521_ (
    .A(_193_),
    .B(_195_),
    .Y(_006_[4])
  );
  NOR _522_ (
    .A(j[2]),
    .B(_175_),
    .Y(_196_)
  );
  NAND _523_ (
    .A(_296_),
    .B(_174_),
    .Y(_197_)
  );
  NOR _524_ (
    .A(_035_),
    .B(_197_),
    .Y(_198_)
  );
  NAND _525_ (
    .A(reset_L),
    .B(inic2[3]),
    .Y(_199_)
  );
  NAND _526_ (
    .A(data_in_SP),
    .B(_198_),
    .Y(_200_)
  );
  NOR _527_ (
    .A(_198_),
    .B(_199_),
    .Y(_201_)
  );
  NOT _528_ (
    .A(_201_),
    .Y(_202_)
  );
  NAND _529_ (
    .A(_200_),
    .B(_202_),
    .Y(_006_[3])
  );
  NAND _530_ (
    .A(_168_),
    .B(_196_),
    .Y(_203_)
  );
  NOR _531_ (
    .A(data_in_SP),
    .B(_203_),
    .Y(_204_)
  );
  NAND _532_ (
    .A(reset_L),
    .B(inic2[2]),
    .Y(_205_)
  );
  NAND _533_ (
    .A(_203_),
    .B(_205_),
    .Y(_206_)
  );
  NOT _534_ (
    .A(_206_),
    .Y(_207_)
  );
  NOR _535_ (
    .A(_204_),
    .B(_207_),
    .Y(_006_[2])
  );
  NAND _536_ (
    .A(_182_),
    .B(_196_),
    .Y(_208_)
  );
  NOR _537_ (
    .A(data_in_SP),
    .B(_208_),
    .Y(_209_)
  );
  NAND _538_ (
    .A(inic2[1]),
    .B(reset_L),
    .Y(_210_)
  );
  NAND _539_ (
    .A(_208_),
    .B(_210_),
    .Y(_211_)
  );
  NOT _540_ (
    .A(_211_),
    .Y(_212_)
  );
  NOR _541_ (
    .A(_209_),
    .B(_212_),
    .Y(_006_[1])
  );
  NOR _542_ (
    .A(j[2]),
    .B(_190_),
    .Y(_213_)
  );
  NAND _543_ (
    .A(_174_),
    .B(_213_),
    .Y(_214_)
  );
  NAND _544_ (
    .A(inic2[0]),
    .B(reset_L),
    .Y(_215_)
  );
  NAND _545_ (
    .A(_214_),
    .B(_215_),
    .Y(_216_)
  );
  NOT _546_ (
    .A(_216_),
    .Y(_217_)
  );
  NOR _547_ (
    .A(data_in_SP),
    .B(_214_),
    .Y(_218_)
  );
  NOR _548_ (
    .A(_217_),
    .B(_218_),
    .Y(_006_[0])
  );
  NAND _549_ (
    .A(_012_),
    .B(_055_),
    .Y(_219_)
  );
  NAND _550_ (
    .A(reset_L),
    .B(_219_),
    .Y(_220_)
  );
  NOT _551_ (
    .A(_220_),
    .Y(_000_)
  );
  NAND _552_ (
    .A(_297_),
    .B(reset_L),
    .Y(_221_)
  );
  NAND _553_ (
    .A(_297_),
    .B(_174_),
    .Y(_222_)
  );
  NAND _554_ (
    .A(_175_),
    .B(_221_),
    .Y(_223_)
  );
  NAND _555_ (
    .A(_222_),
    .B(_223_),
    .Y(_008_[0])
  );
  NAND _556_ (
    .A(_298_),
    .B(reset_L),
    .Y(_224_)
  );
  NAND _557_ (
    .A(_175_),
    .B(_224_),
    .Y(_225_)
  );
  NAND _558_ (
    .A(_035_),
    .B(_190_),
    .Y(_226_)
  );
  NAND _559_ (
    .A(_174_),
    .B(_226_),
    .Y(_227_)
  );
  NAND _560_ (
    .A(_225_),
    .B(_227_),
    .Y(_008_[1])
  );
  NAND _561_ (
    .A(_296_),
    .B(reset_L),
    .Y(_228_)
  );
  NAND _562_ (
    .A(_174_),
    .B(_189_),
    .Y(_229_)
  );
  NAND _563_ (
    .A(_228_),
    .B(_229_),
    .Y(_230_)
  );
  NAND _564_ (
    .A(_214_),
    .B(_230_),
    .Y(_008_[2])
  );
  NAND _565_ (
    .A(_013_),
    .B(_055_),
    .Y(_231_)
  );
  NAND _566_ (
    .A(reset_L),
    .B(_231_),
    .Y(_232_)
  );
  NOR _567_ (
    .A(_013_),
    .B(_055_),
    .Y(_233_)
  );
  NOR _568_ (
    .A(_232_),
    .B(_233_),
    .Y(_009_[0])
  );
  NOR _569_ (
    .A(k[1]),
    .B(_233_),
    .Y(_234_)
  );
  NOT _570_ (
    .A(_234_),
    .Y(_235_)
  );
  NAND _571_ (
    .A(reset_L),
    .B(_235_),
    .Y(_236_)
  );
  NAND _572_ (
    .A(k[1]),
    .B(_233_),
    .Y(_237_)
  );
  NOT _573_ (
    .A(_237_),
    .Y(_238_)
  );
  NOR _574_ (
    .A(_236_),
    .B(_238_),
    .Y(_009_[1])
  );
  NAND _575_ (
    .A(_014_),
    .B(_237_),
    .Y(_239_)
  );
  NOR _576_ (
    .A(_014_),
    .B(_237_),
    .Y(_240_)
  );
  NAND _577_ (
    .A(reset_L),
    .B(_239_),
    .Y(_241_)
  );
  NOR _578_ (
    .A(_240_),
    .B(_241_),
    .Y(_009_[2])
  );
  NAND _579_ (
    .A(i[0]),
    .B(_055_),
    .Y(_242_)
  );
  NAND _580_ (
    .A(reset_L),
    .B(_242_),
    .Y(_243_)
  );
  NOR _581_ (
    .A(i[0]),
    .B(_055_),
    .Y(_244_)
  );
  NOR _582_ (
    .A(_243_),
    .B(_244_),
    .Y(_245_)
  );
  NOT _583_ (
    .A(_245_),
    .Y(_005_[0])
  );
  NOR _584_ (
    .A(_295_),
    .B(_244_),
    .Y(_246_)
  );
  NOR _585_ (
    .A(_299_),
    .B(_246_),
    .Y(_247_)
  );
  NAND _586_ (
    .A(_131_),
    .B(_247_),
    .Y(_005_[1])
  );
  NAND _587_ (
    .A(i[2]),
    .B(_131_),
    .Y(_248_)
  );
  NAND _588_ (
    .A(_134_),
    .B(_248_),
    .Y(_005_[2])
  );
  NAND _589_ (
    .A(reset_L),
    .B(valid_SP_Estruc),
    .Y(_249_)
  );
  NOT _590_ (
    .A(_249_),
    .Y(_250_)
  );
  NAND _591_ (
    .A(_055_),
    .B(_250_),
    .Y(_251_)
  );
  NAND _592_ (
    .A(Aux1),
    .B(_249_),
    .Y(_252_)
  );
  NOT _593_ (
    .A(_252_),
    .Y(_253_)
  );
  NAND _594_ (
    .A(_086_),
    .B(_253_),
    .Y(_254_)
  );
  NOR _595_ (
    .A(_015_),
    .B(_086_),
    .Y(_255_)
  );
  NOR _596_ (
    .A(_057_),
    .B(_255_),
    .Y(_256_)
  );
  NAND _597_ (
    .A(_254_),
    .B(_256_),
    .Y(_257_)
  );
  NAND _598_ (
    .A(_251_),
    .B(_257_),
    .Y(_010_)
  );
  NAND _599_ (
    .A(reset_L),
    .B(inic[7]),
    .Y(_258_)
  );
  NOR _600_ (
    .A(_060_),
    .B(_258_),
    .Y(_259_)
  );
  NOT _601_ (
    .A(_259_),
    .Y(_260_)
  );
  NAND _602_ (
    .A(_064_),
    .B(_260_),
    .Y(_007_[7])
  );
  NAND _603_ (
    .A(_030_),
    .B(_213_),
    .Y(_261_)
  );
  NOT _604_ (
    .A(_261_),
    .Y(_262_)
  );
  NOR _605_ (
    .A(j[2]),
    .B(_031_),
    .Y(_263_)
  );
  NAND _606_ (
    .A(_189_),
    .B(_263_),
    .Y(_264_)
  );
  NAND _607_ (
    .A(cont[0]),
    .B(_261_),
    .Y(_265_)
  );
  NAND _608_ (
    .A(reset_L),
    .B(_265_),
    .Y(_266_)
  );
  NOR _609_ (
    .A(cont[0]),
    .B(_261_),
    .Y(_267_)
  );
  NOR _610_ (
    .A(_266_),
    .B(_267_),
    .Y(_268_)
  );
  NOT _611_ (
    .A(_268_),
    .Y(_001_[0])
  );
  NOR _612_ (
    .A(cont[1]),
    .B(_267_),
    .Y(_269_)
  );
  NOT _613_ (
    .A(_269_),
    .Y(_270_)
  );
  NAND _614_ (
    .A(cont[1]),
    .B(_267_),
    .Y(_271_)
  );
  NAND _615_ (
    .A(_270_),
    .B(_271_),
    .Y(_272_)
  );
  NAND _616_ (
    .A(reset_L),
    .B(_272_),
    .Y(_001_[1])
  );
  NAND _617_ (
    .A(_289_),
    .B(_261_),
    .Y(_273_)
  );
  NAND _618_ (
    .A(reset_L),
    .B(_273_),
    .Y(_274_)
  );
  NAND _619_ (
    .A(flag3[0]),
    .B(_262_),
    .Y(_275_)
  );
  NOR _620_ (
    .A(_289_),
    .B(_264_),
    .Y(_276_)
  );
  NOR _621_ (
    .A(_274_),
    .B(_276_),
    .Y(_004_[0])
  );
  NAND _622_ (
    .A(_290_),
    .B(_275_),
    .Y(_277_)
  );
  NAND _623_ (
    .A(reset_L),
    .B(_277_),
    .Y(_278_)
  );
  NAND _624_ (
    .A(flag3[1]),
    .B(_276_),
    .Y(_279_)
  );
  NOT _625_ (
    .A(_279_),
    .Y(_280_)
  );
  NOR _626_ (
    .A(_278_),
    .B(_280_),
    .Y(_004_[1])
  );
  NAND _627_ (
    .A(_019_),
    .B(_279_),
    .Y(_281_)
  );
  NOR _628_ (
    .A(_019_),
    .B(_279_),
    .Y(_282_)
  );
  NAND _629_ (
    .A(reset_L),
    .B(_281_),
    .Y(_283_)
  );
  NOR _630_ (
    .A(_282_),
    .B(_283_),
    .Y(_004_[2])
  );
  NOR _631_ (
    .A(_035_),
    .B(_176_),
    .Y(_284_)
  );
  NAND _632_ (
    .A(reset_L),
    .B(inic2[7]),
    .Y(_285_)
  );
  NAND _633_ (
    .A(data_in_SP),
    .B(_284_),
    .Y(_286_)
  );
  NOR _634_ (
    .A(_284_),
    .B(_285_),
    .Y(_287_)
  );
  NOT _635_ (
    .A(_287_),
    .Y(_288_)
  );
  NAND _636_ (
    .A(_286_),
    .B(_288_),
    .Y(_006_[7])
  );
  (* src = "Serial_Paralelo_Estruc.v:40" *)
  DFF _637_ (
    .C(clk_32f),
    .D(_007_[0]),
    .Q(inic[0])
  );
  (* src = "Serial_Paralelo_Estruc.v:40" *)
  DFF _638_ (
    .C(clk_32f),
    .D(_007_[1]),
    .Q(inic[1])
  );
  (* src = "Serial_Paralelo_Estruc.v:40" *)
  DFF _639_ (
    .C(clk_32f),
    .D(_007_[2]),
    .Q(inic[2])
  );
  (* src = "Serial_Paralelo_Estruc.v:40" *)
  DFF _640_ (
    .C(clk_32f),
    .D(_007_[3]),
    .Q(inic[3])
  );
  (* src = "Serial_Paralelo_Estruc.v:40" *)
  DFF _641_ (
    .C(clk_32f),
    .D(_007_[4]),
    .Q(inic[4])
  );
  (* src = "Serial_Paralelo_Estruc.v:40" *)
  DFF _642_ (
    .C(clk_32f),
    .D(_007_[5]),
    .Q(inic[5])
  );
  (* src = "Serial_Paralelo_Estruc.v:40" *)
  DFF _643_ (
    .C(clk_32f),
    .D(_007_[6]),
    .Q(inic[6])
  );
  (* src = "Serial_Paralelo_Estruc.v:40" *)
  DFF _644_ (
    .C(clk_32f),
    .D(_007_[7]),
    .Q(inic[7])
  );
  (* src = "Serial_Paralelo_Estruc.v:40" *)
  DFF _645_ (
    .C(clk_32f),
    .D(_006_[0]),
    .Q(inic2[0])
  );
  (* src = "Serial_Paralelo_Estruc.v:40" *)
  DFF _646_ (
    .C(clk_32f),
    .D(_006_[1]),
    .Q(inic2[1])
  );
  (* src = "Serial_Paralelo_Estruc.v:40" *)
  DFF _647_ (
    .C(clk_32f),
    .D(_006_[2]),
    .Q(inic2[2])
  );
  (* src = "Serial_Paralelo_Estruc.v:40" *)
  DFF _648_ (
    .C(clk_32f),
    .D(_006_[3]),
    .Q(inic2[3])
  );
  (* src = "Serial_Paralelo_Estruc.v:40" *)
  DFF _649_ (
    .C(clk_32f),
    .D(_006_[4]),
    .Q(inic2[4])
  );
  (* src = "Serial_Paralelo_Estruc.v:40" *)
  DFF _650_ (
    .C(clk_32f),
    .D(_006_[5]),
    .Q(inic2[5])
  );
  (* src = "Serial_Paralelo_Estruc.v:40" *)
  DFF _651_ (
    .C(clk_32f),
    .D(_006_[6]),
    .Q(inic2[6])
  );
  (* src = "Serial_Paralelo_Estruc.v:40" *)
  DFF _652_ (
    .C(clk_32f),
    .D(_006_[7]),
    .Q(inic2[7])
  );
  (* src = "Serial_Paralelo_Estruc.v:40" *)
  DFF _653_ (
    .C(clk_32f),
    .D(_001_[0]),
    .Q(cont[0])
  );
  (* src = "Serial_Paralelo_Estruc.v:40" *)
  DFF _654_ (
    .C(clk_32f),
    .D(_001_[1]),
    .Q(cont[1])
  );
  (* src = "Serial_Paralelo_Estruc.v:40" *)
  DFF _655_ (
    .C(clk_32f),
    .D(_002_[0]),
    .Q(data_out_SP_Estruc[0])
  );
  (* src = "Serial_Paralelo_Estruc.v:40" *)
  DFF _656_ (
    .C(clk_32f),
    .D(_002_[1]),
    .Q(data_out_SP_Estruc[1])
  );
  (* src = "Serial_Paralelo_Estruc.v:40" *)
  DFF _657_ (
    .C(clk_32f),
    .D(_002_[2]),
    .Q(data_out_SP_Estruc[2])
  );
  (* src = "Serial_Paralelo_Estruc.v:40" *)
  DFF _658_ (
    .C(clk_32f),
    .D(_002_[3]),
    .Q(data_out_SP_Estruc[3])
  );
  (* src = "Serial_Paralelo_Estruc.v:40" *)
  DFF _659_ (
    .C(clk_32f),
    .D(_002_[4]),
    .Q(data_out_SP_Estruc[4])
  );
  (* src = "Serial_Paralelo_Estruc.v:40" *)
  DFF _660_ (
    .C(clk_32f),
    .D(_002_[5]),
    .Q(data_out_SP_Estruc[5])
  );
  (* src = "Serial_Paralelo_Estruc.v:40" *)
  DFF _661_ (
    .C(clk_32f),
    .D(_002_[6]),
    .Q(data_out_SP_Estruc[6])
  );
  (* src = "Serial_Paralelo_Estruc.v:40" *)
  DFF _662_ (
    .C(clk_32f),
    .D(_002_[7]),
    .Q(data_out_SP_Estruc[7])
  );
  (* src = "Serial_Paralelo_Estruc.v:40" *)
  DFF _663_ (
    .C(clk_32f),
    .D(_010_),
    .Q(valid_SP_Estruc)
  );
  (* src = "Serial_Paralelo_Estruc.v:40" *)
  DFF _664_ (
    .C(clk_32f),
    .D(_005_[0]),
    .Q(i[0])
  );
  (* src = "Serial_Paralelo_Estruc.v:40" *)
  DFF _665_ (
    .C(clk_32f),
    .D(_005_[1]),
    .Q(i[1])
  );
  (* src = "Serial_Paralelo_Estruc.v:40" *)
  DFF _666_ (
    .C(clk_32f),
    .D(_005_[2]),
    .Q(i[2])
  );
  (* src = "Serial_Paralelo_Estruc.v:40" *)
  DFF _667_ (
    .C(clk_32f),
    .D(_008_[0]),
    .Q(j[0])
  );
  (* src = "Serial_Paralelo_Estruc.v:40" *)
  DFF _668_ (
    .C(clk_32f),
    .D(_008_[1]),
    .Q(j[1])
  );
  (* src = "Serial_Paralelo_Estruc.v:40" *)
  DFF _669_ (
    .C(clk_32f),
    .D(_008_[2]),
    .Q(j[2])
  );
  (* src = "Serial_Paralelo_Estruc.v:40" *)
  DFF _670_ (
    .C(clk_32f),
    .D(_009_[0]),
    .Q(k[0])
  );
  (* src = "Serial_Paralelo_Estruc.v:40" *)
  DFF _671_ (
    .C(clk_32f),
    .D(_009_[1]),
    .Q(k[1])
  );
  (* src = "Serial_Paralelo_Estruc.v:40" *)
  DFF _672_ (
    .C(clk_32f),
    .D(_009_[2]),
    .Q(k[2])
  );
  (* src = "Serial_Paralelo_Estruc.v:40" *)
  DFF _673_ (
    .C(clk_32f),
    .D(_003_),
    .Q(flag2)
  );
  (* src = "Serial_Paralelo_Estruc.v:40" *)
  DFF _674_ (
    .C(clk_32f),
    .D(_000_),
    .Q(Aux1)
  );
  (* src = "Serial_Paralelo_Estruc.v:40" *)
  DFF _675_ (
    .C(clk_32f),
    .D(_004_[0]),
    .Q(flag3[0])
  );
  (* src = "Serial_Paralelo_Estruc.v:40" *)
  DFF _676_ (
    .C(clk_32f),
    .D(_004_[1]),
    .Q(flag3[1])
  );
  (* src = "Serial_Paralelo_Estruc.v:40" *)
  DFF _677_ (
    .C(clk_32f),
    .D(_004_[2]),
    .Q(flag3[2])
  );
endmodule
